### ISSUE TITLE
Collection of Labels Layer feature requests

### ISSUE THREAD

**Issue by hectormz** [napari/napari#1142]
## 🚀 Feature

Here are a collection of Labels Layer feature requests/ideas I've accumulated recently.

## Motivation

I've been using the Label Layers more, and have some ideas for new enhancements. For convenience or conversation, I've included them all here, but can break this up into many issues if that is useful.

### Fill label with double click on paint brush
There are many using labels that will likely create a closed contour with the paint brush, and then use the fill tool to flood fill. Switching the tool can be done by clicking the fill tool icon, or the `f` key.

After closing a contour, it would be nice to double-click within the contour (while still on the brush tool), which would then fill the area. This would only be done if the user is clicking within a closed contour. And it's up for debate if the color/label id must match (fill does not require this). 

All these capabilities exist, it's just automating tool changing etc

### Scroll through stack
When in fill, pick or brush mode, mouse scrolling does nothing. Switching to pan/zoom mode permanently (or temporarily with space bar) allows for zooming. I'd like to scroll through the dimensions of the stack somehow. This may relate to #1141 , and perhaps when in fill/pick/brush mode, `ctrl + scroll` or just `scroll` would scroll through image dimensions

### Convert Image layer to Labels layer
It would be nice to be able to load an image stack into `napari` and convert it to a labels layer. This can be done by a context menu when right clicking on eligible image layers. I think the only rule to determine eligibility would whether or not the `dtype` of the image is a type of `int` or perhaps if the image is only made of `0, 1`. When converting the image layer to a label layer, it could be upgraded to `int32` if not already the case.

### Select label instead of painting
I like the ability to select regions instead of painting (for visibility or accuracy concerns) like in [`ImageJ`'s `Segmentation Editor`](https://imagej.net/Segmentation_Editor):

![segmentation editor](https://imagej.net/_images/7/7c/Segmentation_Editor_3.png "Segmentation Editor")
We could add a tool in addition to the paintbrush, where with crosshairs, you could select perimeter around a region, and then add/remove it the label with another click/key press. If it's not clear, this would involve drawing the perimeter between pixels/voxels instead of painting the pixels directly.

### Contour view of labels
Visually similar to the selection method mentioned above. It could be useful to have a toggle that displays contours of labels instead of shaded regions. This might provided better/different clarity in some situations than just reducing opacity of the layer.

### Consider Eraser tool
When switching between tools, or when I haven't erased a label in awhile, I forget that erasing a label is done by painting with a "0 label". It might be worthwhile to add an eraser tool that has the same functionality, but might be easier to find.

**Comment by VolkerH** [comment]
Having worked with the labels editor recently as well I second most of these suggestions. 

It took me a while to figure out how to perform basic operations on connected components (hence my recent pull request with changes to the tutorial).

In particular operations such as  

* "erase/delete connected component" (rather than fill with 0) or 
* "create connected component" (drawing a contour that is filled automatically with a integer label on completion of the contour) 

would make this workflow more efficient, with less switching between tools and more intuitive. This might transform the "paint tool" (working on pixels)  feel of  the label editor  into a feel of a "connected component" or "object editor". 

However, for me the biggest hurdle with using the label editor was the lag between drawing and seeing the update. There already have been great performance increases since the first versions but it is still not quite at the level where one would want to label large amounts of data.

**Comment by sofroniewn** [comment]
This is great @hectormz! Will take me a little to go through each of these / think how to break them out into their own issues etc, but I love this - so helpful to hear. Also thanks @VolkerH for weighing in too. 

> However, for me the biggest hurdle with using the label editor was the lag between drawing and seeing the update. There already have been great performance increases since the first versions but it is still not quite at the level where one would want to label large amounts of data.

This one is sitting at #713 but is limited by vispy requiring a 0-1 scaling before sending data to the gpu. We're probably going to need to expose a low-level vispy parameter that will allow us to by-pass this scaling, and given how big an improvement it will be, we should probably do it sooner rather than later!!

**Comment by VolkerH** [comment]
After attending a webinar on [QuPath](https://qupath.github.io/) yesterday, and seeing some of the nice annotation tools therein, I would like to add two more feature requests for consideration. Haven't worked with QuPath myself, but these seem sensible features.

### Modifier key for paintbrush - don't cut into existing labels

In QuPath you can press a modifier key (not sure whether CTRL/ALT/SHIFT) while using the brush tool and it will prevent any drawing into existing labels (other than the background). This is very useful when objects are touching, allows for quicker annotation for a second object if the first one has been carefully outlined already - no risk of cutting in.

### Option to scale brush size with zoom level 
(moved into separate issue #1419 by @kevinyamauchi )

Scale the brush size up as you zoom out (or keep the brush size constant in canvas pixels, but variable in data pixels). The idea is that one typically wants to annotate regions coarsely when zoomed out and in more detail when zoomed in. This would prevent a lot of clicking back and forth.
This may have to be a separate mode, as I can imagine it can lead to confusion in some cases. 

The webinar will be uploaded to youtube we were told but I'm not sure whether it is going to be a public video. If so, I will link to it here with time markers for the relevant sections, as the video explanation is probably much clearer than my attempt to summarize it.

**Comment by sofroniewn** [comment]
Both of these sound like great features! Thanks @VolkerH for adding!!

**Comment by VolkerH** [comment]
Just to add the reference for the last two features as they are implemented in QuPath:

https://www.youtube.com/watch?v=4An5n6Y_rRI

* scale brush size with zoom is at minute 29:40
* don't cut into other labels is at 31:30

**Comment by kevinyamauchi** [comment]
> Modifier key for paintbrush - don't cut into existing labels

Amazing! Love it!

**Comment by sofroniewn** [comment]
Adding #1235 from @jni

**Comment by sofroniewn** [comment]
Also linking #1245 and #716

**Comment by liu-ziyang** [comment]
As I digging a bit on the idea behind the issue, I found the common theme of "an explicit switch between tool is tedious, I want to be able to temporarily switch my tool using a specific gesture, be it key invoke or special clicks"

I am going to experiment using control keys (control, alt, commands, etc) to temporarily switch tool, as well as adding the eraser as suggested. And see how people like the new way to toggle their current tool, the key is negotiable, pardon me if I choose the suboptimal one that people are most familiar with since I have no previous experience with a drawing tool that may already set the conventions

**Comment by jni** [comment]
- [x] change brush shape to a circle (as requested on image.sc): https://forum.image.sc/t/pixel-is-not-a-square/39455

(moved into separate issue #1418 by @kevinyamauchi )

**Comment by sofroniewn** [comment]
> change brush shape to a circle (as requested on image.sc): https://forum.image.sc/t/pixel-is-not-a-square/39455

Should be very doable. Might take a tiny hit on performance, but shouldn't be too bad. Basically these two slice calls https://github.com/napari/napari/blob/master/napari/layers/labels/labels.py#L689-L697 and https://github.com/napari/napari/blob/master/napari/layers/labels/labels.py#L704 will now need to be optionally done based on a center radius instead of center bounding box (we should be able to find away to just have one call to this new method too probably) and we'll need to make a new `circle_pixmap` for the cursor, like our `square_pixmap` here https://github.com/napari/napari/blob/f706a4157cf80e6e0b0d3f21adc0a1c3f7c3b410/napari/_qt/utils.py#L75-L85 which then get's used here https://github.com/napari/napari/blob/master/napari/_qt/qt_viewer.py#L430

**Comment by kevinyamauchi** [comment]
I broke out a couple of the features here as individual issues, as I thought they could make "good first issues".

- Change label brush to a circle (https://github.com/napari/napari/issues/1142#issuecomment-649548968): #1418 
- Scale brush size with zoom level (https://github.com/napari/napari/issues/1142#issuecomment-621557412): #1419

**Comment by sofroniewn** [comment]
Looking at this again, it looks like the only 3 remaining requested features that are not implemented are

- [ ] Scale brush size with zoom level #1419
- [ ] Convert image to labels #1442
- [ ] Contour view of labels #1858

Once those are implemented I think we can close this issue

**Comment by jni** [comment]
Re-reading this issue, I'm so happy with the progress we've made with our labels painting! BUT, I'm going to add a couple more to the list:

- [ ] labels paintbrushes should respect anisotropic scales #2368 
- [ ] labels should be able to paint into a subset of dimensions, not just two or all #2369

**Comment by psobolewskiPhD** [comment]
Quick update on things requested here and still outstanding:
- [ ] Some sort of auto-fill/double-click-to-fill mechanism for closed contours. We got close with this PR: https://github.com/napari/napari/pull/5006 (**Edit:** @jni: see issue #8363.)
- [ ] Erase/delete connected component: this is still Fill with 0, but easier thanks to `X` binding (set to 0, then set back). From some recent training, it's clear that is not super intuitive, but people adjust. Still, having the Eraser work better would help.
- [ ] Scale brush with zoom, see https://github.com/napari/napari/issues/1419
- [ ] use anisotropic scale when painting in ndim  https://github.com/napari/napari/issues/2368

**Comment by DarioS** [comment]
I would like it if two masks are touching that the line between them be drawn.

<img width="285" height="145" alt="Image" src="https://github.com/user-attachments/assets/5bbbbbe0-aa80-4dc8-952d-1f6d03848fc1" />

Note how cells 1 and 2 look separate if contour set to 1, but not the ones below them, which become a large red blob.

**Comment by psobolewskiPhD** [comment]
Can you clarify: It looks like you have a boolean mask or single label. For the case of 1, 2 there is a bit of background between them, but for the others there isn't as far as I can tell. The contours outline the connected components, so you need to somehow separate what should be an independent object, e.g. using watershed or even the eraser tool.

**Comment by DarioS** [comment]
Sorry about the spurious distraction. [EBImage](https://bioconductor.org/packages/release/bioc/html/EBImage.html)'s `writeImage` function silently thresholds at 1 upon export.

```r
> image <- Image(matrix(c(1, 1, 2, 2), ncol = 2))
> image
Image 
  colorMode    : Grayscale 
  storage.mode : double 
  dim          : 2 2 
  frames.total : 1 
  frames.render: 1 

imageData(object)[1:2,1:2]
     [,1] [,2]
[1,]    1    2
[2,]    1    2
> writeImage(image, "/tmp/issue.tiff")
> readImage("/tmp/issue.tiff")
Image 
  colorMode    : Grayscale 
  storage.mode : double 
  dim          : 2 2 
  frames.total : 1 
  frames.render: 1 

imageData(object)[1:2,1:2]
     [,1] [,2]
[1,]    1    1
[2,]    1    1
```

Previously, there were two objects, denoted by 1 and 2. But, the values in exported file are truncated at 1.
