### ISSUE TITLE
Error Handling Design Proposal

### ISSUE THREAD

**Issue by liu-ziyang** [napari/napari#1395]
## Motivation
There are a lot of reported issues on the napari repo related to error handling. We need to have a unified solution for error reporting and logging, including the plugin error handling/logging.

## Meta Analysis
Expanding on the work and analysis of the [event handler](https://github.com/napari/napari/pull/1040), I found that the current flow of error handling is not intuitive for a few reasons:
- The error handling framework is now largely built on top of qt event loop, we leverage qt to deal with error and make sure exceptions are caught and blocked on malfunctioning code path/user action. Resulting in the lack of a middle layer to capture errors, and many internal errors propagate up the stack, and hence hard to enforce a MVC methodology since the flow itself is not controller centric.
- Developers would not have a sense of safety without comprehensive understanding of the existing codebase, they would not be able to declare and raise exceptions as freely in their code. It can be overwhelming to write code that may raise an exception when the consequences are unknown (would it crash the application if an exception is raised here?), even if throwing an exception is the right thing to do. 
- There is no consensus of how errors should be handled, resulting in possible dispersion of code style and different practices when coming down to logging, notifications, etc.

## Case Analysis
- [Bug report](https://github.com/napari/napari/issues/1349): SystemError on exit with perfmon and PyQt5
- [Bug report](https://github.com/napari/napari/issues/1336): Napari crash on Windows 10 - QT issue?
- [Bug report](https://github.com/napari/napari/issues/1347): Napari 0.3.4 release crashes when switching to volume rendering

## Design principles:
- Isolating error handling from the view layer, continuing decoupling of view class to avoid crashing on errors. The end goal is to have the UI(view) to be bullet-proof, regardless of errors going on behind the scene (model layers) on the controller side, and unify handling of such errors to the controller end, which gives peace of mind to both view and model implementations. Rely on the Qt error handling only for view related issues
- Enhance error message propagation, and make them visible/interactive to the user. The end goal is to make sure the user understands what went wrong, and how to proceed if possible. Such error messages should be displayed consistently across different types of errors, too.
- Provide unified error handling flow to be used consistently throughout the codebase, defines and extend logging functions to be used across codebase to track errors, while using standard log level to control robustness of such logging
 
## Design considerations
- Scope of the work: These changes are going to be long term changes unlikely addressed by a single PR. We need to carefully scope the steps to make sure we are heading in the right direction without stepping on our toes
- The enhance of the controller work has some overlap in concept with event handler, and we should avoid having duplicate effort and should coordinate closely to stay DRY[2]
- Controllers should include exception handling as first class citizens, and during implementation, not only should we look at the current implementation of model classes to ensure best compatibility, we also need to take the future into consideration. Think what if the model class gets replaced? What exception class should the model class declare to be more future proof? Is it necessary to also capture generic runtime error from potential underlying library exception leaks?
- Unification of logging levels/library can be tricky when used in combination with underlying libraries, we may need a log config file to help gauge flooding messages when under a debug/trace mode
- Does it make sense to treat exceptions as an event and handled the same way in the event handler?
- How helpful would it be to provide a function that calls back in a try catch block? Or should we only provide a helper function for the exception handler?
- Currently plugin errors are all wrapped and reported as PluginCallError, and aggregated in a console to view them. This seems a reasonable approach to capture the wide range of possible errors raised from the plugins, and make sure they don’t crash the main application. However worth noting that since plugin can be any arbitrary code, subject to malicious activity and unintended side effects, it may threaten the main application by taking away memory/cpu/gpu resources and potentially make the main application crash/stop responding. We would not discuss/design for it immediately.

## Implementation plan
- Extend global error catch as proposed [here](https://github.com/napari/napari/pull/794), this will give us highest level of catch-all before we get to implement more detailed error handling mechanisms
- Complete event handler refactor, which will pave way for centralizing controller
- Create error handler library to unify logging/reporting practices
- Refactor/rename folder structure to isolate out model, view and controller. Decouple model from controller as well
- Update controllers to have built in error handling logic, make sure to use the created error handler library to stay DRY[2], see appendix for some code snippet
- Update view to reflect on controller errors to give user more intuitive messages about the error
- Build error reporting method to collect errors automatically, there are some existing solutions like [sentry.io](https://sentry.io/welcome/), [google cloud](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/error_reporting/api), [bugsnag](https://www.bugsnag.com/)

## Appendix
[1] [MVC pattern in python](https://www.giacomodebidda.com/mvc-pattern-in-python-introduction-and-basicmodel/)
[2] [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

**Comment by tlambert03** [comment]
These are some great principles for us to think about going forward @ziyangczi.  Thanks.
For addressing the near-term problem of qt crashing out to the consol, and users wondering why nothing happened, perhaps some concrete next steps could include:
- [x] pare down #794 to the bare minimum required to catch an unhandled exception, and emit an event (already implemented there in `ExceptionHandler.error.emit()`). All display of errors in the GUI should probably be in a followup.
- [x] The end goal of #794 should only be to make sure that we never crash back to the command line. And the “default behavior” (until we hook up a GUI error message) should be to simply print the traceback to the console… effectively recovering what the “default python behavior” is for almost every other (non Qt) program.
- [x] Later PRs should think about a better version of the `_show_error_dialog` function in there. We talked about having the help bar at the bottom lighting up somehow to indicate an error. I do like avoiding popups when possible, but I also want it to be totally obvious when an error occurs… and clear how to get more info.
- [ ] I can imagine multiple “levels” of error signals passed by the error handler in #794… perhaps corresponding to the logging levels? And everything but “critical” level might just make the entire status bar have a red background (something like the VScode bottom bar), with something like a “get details” button (or a clickable :warning: icon) that shows something more. A critical error should pop up a message. It’s an open discussion what constitutes “critical”.  This will likely require some reworking of the status bar itself.
- [ ] We will of course then need logic in the ExceptionHandler to delegate exceptions to either the console, the help status bar, or a QMessageBox based on some criteria.  That might mean us "guessing" something about the exception, or perhaps revisiting the concept of special napari Exception classes that indicate something about how the exception should be handled.

**Comment by liaprins-czi** [comment]
Below is a link to a design for the hover state. When user hovers on an error message it will keep it from fading out while they are hovering, as soon as they stop hovering it will reset the timer before it starts to fade away again.

https://www.figma.com/proto/Aq1PhG2tVTodGZnSBe0nui/Error-Handling?node-id=69%3A4&viewport=-2308%2C201%2C1&scaling=min-zoom

On hover the message changes to have a border (#6A7380, same color as the scroll bar in the layers panel).

Also, I think the time the message stays visible before it fades out should be at least 5 seconds, otherwise it's too rushed from them to read it and make sense of what it says.

**Comment by sofroniewn** [comment]
This is coming along very nicely, with the merge of #1511. I think there are still some followups and improvements, like around deciding when the display to console vs GUI, and different levels of errors, so I will leave this open, but it has come a long way!!

**Comment by jni** [comment]
@sofroniewn @ziyangczi we're currently in this middle ground where errors on `napari path/to/image` are caught by the UI, but it is a completely unhelpful dialog, because I can't view a full traceback (let alone copy it to the clipboard!). What do people think about reserving the error catching for the bundled app or as an opt-in until this proposal (which is great, to be clear) is more fully implemented? And/or prioritising fleshing out that dialog.

**Comment by liu-ziyang** [comment]
@jni supposedly the exiting changes would push the error messages to the console same as default python behavior, I am surprised to see otherwise, are you able to find a reproducible pattern?

**Comment by jni** [comment]
Well, thanks to #1717, you can do `pip install -U ome-zarr` then `napari https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr` right now on master and see the errors get caught by the UI, at least on Mac. I think it's the same on Linux actually, so it's probably/sadly not a weird interaction with our `pythonw` hack.

**Comment by liu-ziyang** [comment]
> Well, thanks to #1717, you can do `pip install -U ome-zarr` then `napari https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr` right now on master and see the errors get caught by the UI, at least on Mac. I think it's the same on Linux actually, so it's probably/sadly not a weird interaction with our `pythonw` hack.

sorry for the late reply, this is the error that I see from running this on the commandline: 
```
10:22:11 ERROR PluginError: Error in plugin 'ome_zarr', hook 'napari_get_reader'
  Cause was: ClientConnectorCertificateError(ConnectionKey(host='s3.embassy.ebi.ac.uk', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)'))
    in file: /Users/zliu/PycharmProjects/napari/venv/lib/python3.8/site-packages/aiohttp/connector.py
    at line: 938
     author: The Open Microscopy Team
    package: ome-zarr
        url: https://github.com/ome/ome-zarr-py
    version: 0.0.14

10:22:11 ERROR PluginError: Error in plugin 'builtins', hook 'napari_get_reader'
  Cause was: ValueError('Not a zarr dataset or group: https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr')
    in file: /Users/zliu/PycharmProjects/napari/napari/utils/io.py
    at line: 292
     author: napari team
      email: napari-steering-council@googlegroups.com
    package: napari
        url: https://napari.org
    version: 0.3.9.dev44+gcd1c3329

```

this is actually a special case in the error handling, because this is dealt with by the plugin error handler itself, not the global handling flow. If I understand correctly you are saying we should expose the stack trace for this error, correct?

**Comment by jni** [comment]
> you are saying we should expose the stack trace for this error, correct?

Yup. Errors without stack traces are in most cases useless for debugging. So in all cases the stack trace should be accessible.
