### ISSUE TITLE
Concerns about event handler patterns

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1409]
I apologize for what might be a bit of a frustrating thread, but in working with napari code over the last week or two, I've been bothered by a couple new patterns introduced by the EventHandler.  I know a lot of work has already gone into moving to the new patterns, but I want to raise a couple concerns for discussion before we get too far down this road (also sorry that I didn't realize all of these earlier during review):

- I do like standardizing the “payload” of the event attribute to `event.value`.  However, the event handler throws away everything _but_ `event.value` before passing it on to the listeners… so we’re losing a fair amount of functionality provided by the event object. (I don’t love the alternative pattern of providing a dict for `event.value` when you need more structure).
- I do like standardizing the names of callbacks and methods when possible, but we’ve lost the ability to connect specific callbacks to specific events: now, you only get a single callback `_on_<event_name>_change`, and it is _always_ connected to all registered event_handlers that have an event by that name.
- Similarly, we’ve lost the decorator functionality provided by `EventEmitter.connect` (this is very much like what Ziyang was wanting… which appears to have been there all along):  
```python
events = EmitterGroup(source=self, added=None)
 @events.added
def callback(self, event): 
    ...
```
- I really don’t like the new pattern of having setters “not set” but rather just emitting events, and the callbacks set.
    ```python
    @blending.setter
    def blending(self, blending):
        self.events.blending(blending)

    def _on_blending_change(self, blending):
        self._blending = Blending(blending)
    ```
    I believe this was added for two reasons:
    1. an attempt to avoid needing event blockers
    2. providing the opportunity for the event handler to possibly “reject” the event before it actually gets set.

It strikes me as a bit of a bad code smell that we are potentially going to use _everywhere_.   Is this a pattern that others have seen used elsewhere?  I guess I'd like to hear again the pros and cons of that as people see them.  For me, it's a lot of boilerplate added for two rather rare concerns (if I understand the motivation correctly).

- *added in edit*: as we've already seen... the EventHandler is going to become a monolithic pointer to objects, which has already [caused tests to fail](https://github.com/napari/napari/pull/1391#issuecomment-653939143) without resorting to some tricks using `weakref`

specific or general thoughts welcome.  What do you see as the _core_ (non-negotiable) features of the event handler?  How would you briefly summarize the motivation for the refactor, and do you feel like the implementation is on track given the motivation?

**Update:** I'm going to extract some of comments below and put them here as food for thought:
# Issues/Questions

- [ ] @sofroniewn: where should initialization of our views/ wiring up of the view to the event handler be done (https://github.com/napari/napari/issues/1409#issuecomment-655804373)
- [ ] @sofroniewn: where should object specific functionality like `slicing` of our layer model be done? Where does the slice code live? Where do the sliced objects live? (https://github.com/napari/napari/issues/1409#issuecomment-655804373)
- [ ] @sofroniewn: what does communicating "up" and "down" the hierarchy of our objects look like?(https://github.com/napari/napari/issues/1409#issuecomment-655804373)
- [ ] How should we apply "separation of concerns" here.  Should views know about and use model APIs?  or strictly emit events?
- [ ] Should end-users be able to directly edit the model (as they currently do)?  Or via some controller object?
- [ ] @jni: I think the original motivation was that @shanaxel42 and @ttung found the logic of napari classes a bit convoluted, because events could go directly from the model to the Qt elements, or from the VisPy canvas/nodes to the Qt elements, or from the model to VisPy to the Qt elements (see #1006).(https://github.com/napari/napari/issues/1409#issuecomment-656038929)

**Comment by sofroniewn** [comment]
> I apologize for what might be a bit of a frustrating thread, but in working with napari code over the last week or two, I've been bothered by a couple new patterns introduced by the EventHandler. I know a lot of work has already gone into moving to the new patterns, but I want to raise a couple concerns for discussion before we get too far down this road (also sorry that I didn't realize all of these earlier during review)

That's fine, I think it's actually been good to get stuff in and play with it. I don't think we've burnt any bridges yet. Almost all the changes are happening in private methods with backwards compatible testing, so perfectly fine for us to continue discussion and thinking about ways to improve.

## Answering some questions

> How would you briefly summarize the motivation for the refactor

I think the core motivation is to separate out concerns to make our model and view code more maintainable, easier for new-comers to understand and work one. Secondary motivations are to provide a centralized place for things error handling/ logging/ maybe plugin interactivity/ and controller like functionality (like doing the slicing on our models).

> Do you feel like the implementation is on track given the motivation?

I think some things are getting better, in general I like the direction our view code is trending without having the full models on them, it makes those files easier to understand in isolation and probably the whole system more robust because we don't have our views poking into the models anyplace they want (right now they often poke into `_` methods like `_data_view` or something like that too). We havn't been able to actually remove our models from our views yet, but I think that will be very exciting when we can, and I hope that will come soon.

I think we havn't looked into the larger controller like refactoring yet, like placing the slicing somewhere else, but I'm hoping that will let our model code become simpler too (see #1353).

> What do you see as the core (non-negotiable) features of the event handler? 

I guess at this point it's a full decoupling of our model and view code so that they can only communicate with each other via events. Having a hybrid system is very dangerous. I do think there is a choice between either passing `payloads` around or using a `model` attached to the view, but we shouldn't have both. If we go with the event system then you shouldn't be able to do `view.model` in the way that you can't do `model.view` right now.

> specific or general thoughts welcome.

> - I do like standardizing the “payload” of the event attribute to event.value. However, the event handler throws away everything but event.value before passing it on to the listeners

I'm ok with this, I think it's quite nice if we can get away with it as it really limits what gets passed around which I think improves robustness. We could actually even simplify the whole event system at some point too to bake in this assumption, but I do think it's nice for now to know that we're using something that is a bit more powerful if we need it.

> - I do like standardizing the names of callbacks and methods when possible, but we’ve lost the ability to connect specific callbacks to specific events: now, you only get a single callback _on_<event_name>_change, and it is always connected to all registered event_handlers that have an event by that name.
> - Similarly, we’ve lost the decorator functionality provided by EventEmitter.connect (this is very much like what Ziyang was wanting… which appears to have been there all along):  

Yeah this naming seems undesirable, I'd prefer to move away from this to something more explicit, but agree there are challenges. Fixing this seems like something everyone agrees on.

> I really don’t like the new pattern of having setters “not set” but rather just emitting events, and the callbacks set.

I agree this smells funny, but I've sort of gotten used to it now and it does make for more symmetry with with `_on_*_change` methods in the view. If there was a good way to fix this I'd be open, but I think we need it for now.

> EventHandler is going to become a monolithic pointer to objects

I guess this doesn't bother me too much

## Additional Thoughts

A couple major unresolved things are

- where should initialization of our views/ wiring up of the view to the event handler be done

- where should object specific functionality like `slicing` of our layer model be done? Where does the slice code live? Where do the sliced objects live?

- what does communicating "up" and "down" the hierarchy of our objects look like?

**Comment by liu-ziyang** [comment]
I pretty much agree with all of the observations, in fact I was planning to point them out after my first few attempts at implementing it on more layers. My general take away so far is that this piece would need to be rethought and reworked in future iterations, but this is a more centralized place for future improvements than now, the pain that I am feeling now can almost all directly or indirectly connect to the lack of controller layer, the more we can separate the view from our data model, the closer we will get to an ideal place in the future. That being said, I think it is then a pure tradeoff of what is acceptable in the middle ground before we are able to get to where we are all comfortable. Living in the agile world, my personal take is to make swift changes and continue improving, despite the smell that is going on once we are onboarded with an implementation plan, at the end of the cycle we look and reprioritize again what we can do to make the software overall better.

**Comment by liu-ziyang** [comment]
in the PRs related that are opened today, you can spot a few compromises that I made like passing in dictionaries to events, connecting qt components to event handler so they don't need to track layers, etc. I am pretty much with my eyes closed when I typed those pieces (lol). But simply removing the data model from those classes made me feel this is going to make the overall practice clean and scalable.

**Comment by jni** [comment]
@sofroniewn 

>  we don't have our views poking into the models anyplace they want (right now they often poke into _ methods like _data_view or something like that too).

Well, my feeling now is that this was actually more of a symptom of #1353 (our models being too complex, as pointed out by @pwinston) rather than of the event architecture. There might be a version of #171 and our original architecture of views "having" models in which the view *only* accesses one of the 7 public attributes.

> > EventHandler is going to become a monolithic pointer to objects
> I guess this doesn't bother me too much

Why are you worried about the views poking into objects but ok EventHandlers getting free rein?

@tlambert03 

> What do you see as the core (non-negotiable) features of the event handler? How would you briefly summarize the motivation for the refactor, and do you feel like the implementation is on track given the motivation?

I think the original motivation was that @shanaxel42 and @ttung found the logic of napari classes a bit convoluted, because events could go directly from the model to the Qt elements, or from the VisPy canvas/nodes to the Qt elements, or from the model to VisPy to the Qt elements (see #1006). This resulted in the "six calls to `_set_data`" problem (#613 and links although I can't find your wonderful diagram @tlambert03!), which *was* fixed but only *specifically*, rather than architecturally. There was nothing out there preventing us from having the same or similar problems in the future. So I think that's the main reason that @sofroniewn liked the refactor and that I was in the end convinced to get on board, even though it always bugged me that the refactor was not actually *directly* fixing any bugs or performance issues.

So anyway, I do share your doubts now. @sofroniewn says:

> I think the core motivation is to separate out concerns to make our model and view code more maintainable, easier for new-comers to understand and work on. Secondary motivations are to provide a centralized place for things error handling/ logging/ maybe plugin interactivity/ and controller like functionality (like doing the slicing on our models).

"A centralized place" is starting to sound to me like a nest of global variables, which we in fact are trying to move away from in #1353 . At first I looked at #1376 and I saw a lot of disappearing code, which was nice, but now looking at #1410 for example, I share your concern that we seem to in fact be getting *more* boilerplate.

BUT, we do have some more safety in that the EventHandler can definitely guarantee that events are only processed once. So I guess the question I have, @tlambert03, is what your alternative vision might be for how we deal with models and events. The one thing I *am* clear on is that wherever the global optimum is for this stuff, we are nowhere near it yet. 😂 Whether we are *pointing towards it*, is another question, but even on that I'm not clear.

I'll add for reference @royerloic's original "commandments" for views and models: #171. 

Would certainly love @pwinston to weigh in on how he feels about all these smells. =)

As @sofroniewn mentioned though: no need to panic, nothing public has changed, we can always correct course or even backpedal if it comes to that.

**Comment by tlambert03** [comment]
> makes those files easier to understand in isolation and probably the whole system more robust because we don't have our views poking into the models anyplace they want ... We haven't been able to actually remove our models from our views yet, but I think that will be very exciting when we can...

I think this is probably the key (most consequential) point that i might disagree with.  Or at least I feel that if we're going to go this way, then we need to change our EventHandler dramatically (into a proper controller). Separation of concerns dictates that models be unaware of views, but not that views be unaware of models.  For 25 years, Qt has used the idea that views use the model API directly, so I don't think we can conclude that it's not a robust pattern or that it can't scale.  
I have the same question as @jni: "Why are you worried about the views poking into objects".  This is our own internal API after all...

If we _did_ want to go to a place where the view doesn't see the model except via the event handler, then that event handler needs to become a proper controller, meaning _it_ has a pointer to both the view and the model and makes all of the API calls into each.  Also, it needs to be the thing _receiving_ user requests.

What I really don't like about model setters "not setting" is that the model has lost its place as the source of truth.  The model "setter" now is just making a request to the controller (EventHandler) which is then calling the "real" model setter (the event handler).  If you want the EventHandler/Controller to have that sort of power, then a proper MVC pattern would say that it's really the _controller_ that the end user should be interacting with, and the controller directly calls the model setter API.  That is, we would specifically _discourage_ python users from ever instantiating a model directly... (an example of that is in that [MVC blog post](https://www.giacomodebidda.com/mvc-pattern-in-python-introduction-and-basicmodel/) that @ziyangczi previously linked... though I'm not sure we should necessarily base too much on that post)

> So I guess the question I have, @tlambert03, is what your alternative vision might be for how we deal with models and events. The one thing I am clear on is that wherever the global optimum is for this stuff, we are nowhere near it yet. 😂 Whether we are pointing towards it, is another question, but even on that I'm not clear.

I don't have an immediate answer, but let me sit back and think/read about it and see if I can suggest anything more concrete. But I don't want us to make up our own bespoke patterns ~~based~~.  This is like thesis-material stuff here and I think we should research it and have a complete vision, rather than incrementally try stuff out and see how it feels.

The somewhat unique thing here for a GUI application is that we _want_ our users to be able to touch what we're currently calling the "model".  That _can_ work, but I think we have to acknowledge then that the command line user has a lot of power.  That's kinda fine with me, and as long as the models are emitting the appropriate events when touched, and raising exceptions immediately for invalid requests, I think we could make it work.

If we want the ability to funnel command line requests through some mediator that can accept/reject some request, then I don't think we want the model to be the thing that the user interacts with.  They would use something more akin to a "console view" equivalent of the GUI view.  And the model logic would be reduced even more.  The setter -> event -> callback pattern on our models is mixing classical "controller" behavior with the model itself.

**Comment by tlambert03** [comment]
one more observation (related to point # 2 in the first post):  It used to be quite easy to see what methods in the the whole library were hooked up to particular events, for instance, by searching "`layers.events.added.connect(`".  which is no longer possible.  
I _can_ of course search for `_on_added_changed`, but there's no telling what it's listening to anymore.  so at first impression, though we've removed a fair amount of "...events.<event_name>.connect" lines from the codebase, it's actually been harder for me to figure out the connection graph than it was before

**Comment by tlambert03** [comment]
(forgot to add): relatedly, I have actually made progress in auto-mapping of the connection graph mentioned in #1389, by mocking the `EventEmitter.connect` method in pytest, and running all of our tests to see what gets hooked up.  It works great (still need a good way to visualize it, but I have all the nodes/edges)!  It's not immediately clear to me whether that would be possible with the implicit name-based event connections

**Comment by sofroniewn** [comment]
Closed by #1416 reversion
