### ISSUE TITLE
Meta issue: evented data models

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1490]
We have a number of open PRs now integrating the new evented dataclass (#1475)  and list models (#1444).  I agree with @sofroniewn (https://github.com/napari/napari/pull/1489#discussion_r457582221) that this is working well to identify problem areas in these base objects and iterate before merging them into master.  It does require cleaning up periodic merge conflicts in these PRs, and makes each PR look temporarily larger than it really is... but I think it's worth sticking with it for a bit.  Creating this issue to track them:

### Base PRs

- [x] #1475 adds the new `@dataclass` decorator with `(events=True, properties=True)`, creating a model that emits an event whenever it changes, and providing a concise syntax for getter/setter type transformations.  (This is an implementation of ideas proposed in issues #1436 and #1325)
- [x] #1444 adds a new `EventedList` model - a concrete implementation of `abc.MutableSequence` that emits events when the sequence changes.  It also provides a `NestableEventedList` model that handles nested indexing (eg `my_list[1, 4, -1]`) and bubbles all events emitted by deeply nested children up to the root object.

### Integration PRs

- [ ] #1485 (depends on #1475) turns the new `TextManager` into an evented dataclass.
- [x] #1486 (depends on #1444) uses the `EventedList` in `Dims` ... deprecates some old attributes, and may also bring in the dataclass from #1475 
- [ ] #1489 (depends on #1475) turns the `ViewerModel` into an evented dataclass.

*changes to the `dataclass` decorator or the `EventedList` model in any of these integration PRs should be merged back into either #1444 or #1475 ... and then all of the integration PRs should merge the new change*

### Principles

- the declaration of a model class should be clean and easy to read, with the main attributes front and center, along with type annotations.
- changing any of the main attributes will automatically emit an event, where `event.type` is the name of the attribute and `event.value` is the new value for the attribute. 
- for common type coercion during setting getting (like converting a string to an enum and back) should be possible with minimal boilerplate by passing a transform function to an `Annotated` type declaration.
- while `_on_<name>_set`/`_on_<name>_get` methods can be used to customize event handling and/or value getting/setting... it should be considered a last resort rather than a go-to pattern.  And the need for the override should be evaluated for potential bad designs.

**Comment by sofroniewn** [comment]
These base PRs are now closed, and the integration PRs are well under way

- [x] #1910 Axes
- [x] #1911 ScaleBar
- [x] #1912 Cursor
- [x] #1913 Grid
- [x] #1914 Camera
- [x] #1916 Colormap

We've still got the following open
- [x] #1917 Dims
- [ ] #1485 TextManager
- [ ] #1489 ViewerModel

We've also got an amazing docs PR in progress too
- [ ] #1965 Evented dataclass docs

**Comment by sofroniewn** [comment]
Another thing to do would be add strict type checking, possibly using pydantic, see https://github.com/napari/napari/pull/1965#discussion_r532108851 and #1436 for more discussion

**Comment by sofroniewn** [comment]
We've now switched over to using pydantic with #2042. I'm closing this issue
