### ISSUE TITLE
Add a bot to cancel old builds

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#2651]
## 🧰  Task

Add a bot to close stale/old commits on PRs.

## TODO

- [ ] Docs: Include screenshots on heroku
- [ ] Docs: Refer to the repo of the bot
- [ ] Docs: Token settings / https://github.com/settings/tokens
- [ ] Update original README to include the info on the token

## Motivation

When we push new commits to a branch that is a PR in the repo, we start new actions and workers to run the CI tests.

As more contributors arrive we are running out of workers and are adding many things to the queue, which results in wait times.

## Pitch

We could use a similar approach to the one defined by https://github.com/jupyterlab/jupyterlab-bot

We could use a fork of that repo (so we have access to it) and just use it as is, with some config updates. I can make sure to update the code over that repo (I wrote most of it I think) so we can configure it more easily.

We then configure a github webhook and have this run on heroku (or some other service) We use heroku plus docker as it allows us to run this on the free tier :) 

## Alternatives

There is this action, but seems still insufficient https://github.com/marketplace/actions/cancel-workflow-action as it requires setting multiple workflows for it to work on PRs from forks due to github security model and it can also run out of workers, so if at some point all workers are busy the action would cease to work.

**Comment by sofroniewn** [comment]
I'm finding myself waiting more and more for things as the activity on the project has increased, so probably worth exploring this. Curious what others think. Thoughts @jni?

**Comment by goanpeca** [comment]
Happy to set this up and write docs as needed for any future maintainers :).

We have been very happy users of this for 10 months and counting 👀

**Comment by jni** [comment]
Yeah this sounds great to me, thanks @goanpeca! I just spent a bit of time cancelling builds on scikit-image to get the CI wheels built for a release, so this hits very close to home! 😂

**Comment by goanpeca** [comment]
@sofroniewn could you create a fork of  https://github.com/jupyterlab/jupyterlab-bot inside the napari org, and give me access to it?

I can start setting things up.

**Comment by sofroniewn** [comment]
Done https://github.com/napari/jupyterlab-bot

Let me know if you need increased permissions

**Comment by goanpeca** [comment]
It is now working 🚀 
![image](https://user-images.githubusercontent.com/3627835/117516947-37092700-af60-11eb-8e8b-95208f63d67b.png)

Will leave this issue open to do the following:
- Update development docs to explain what is in place.
- Check that the napari-bot account has the lowest permissions it needs.

Thanks @sofroniewn for the help!

**Comment by sofroniewn** [comment]
> Will leave this issue open to do the following:
> - Update development docs to explain what is in place.
> - Check that the napari-bot account has the lowest permissions it needs.

Happy to leave this open, in which case we can either have it as `0.4` (or `0.4.10` milestone if we think we'll get the work done by then) or we can close and label as `0.4.9` as that is when we did the bulk of the work
