### ISSUE TITLE
Add automation to github and zenhub pipelines

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#2777]
## Task

Add automation to zenhub pipelines:

### Github

- [x] When a PR is opened, make the assigned the author to that PR
- [ ] If someone is added or asked to review a PR, then auto assign the PR to them as well so filtering in the board is clear.
- [ ] If an author opens a PR and it has a Fixes/Closes github reference word, ensure the issue is also assigned to this author.
- [ ] If an author opens a PR and it has a Fixes/Closes github reference word, ensure the PR is also labeled accordingly with the corresponding type.

### Zenhub

- When a reviewer makes a `Request for changes`, move a PR to In Progress, if it was under the Review pipe.
- When all reviewers approved a PR move to Done Pipeline. (Or at least a given number, like 2,3)
