### ISSUE TITLE
Speedup CI Testing.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#3036]
## 🧰 Task

CI has become a bit slow with close to ~20 min turnaround between pushing a commit and having all items green.
It should be possible to speed that up. 

1. caching – a large part of the time is CI is spent creating the venv, caching may be a way to speed things up. 
    - [ ] #2996 is a first step toward caching on linux. 
    - [ ] cache on macOS
    - [ ] cache on windows
 2. Test extremely large dependencies on a single matrix item:
    - [ ] it looks like (py)torch is 1.6G which is more than 2/3 of our venvs, for a single test. Maybe create its own matrix element.
 3. Mark slow test
    - [ ] A few tests use subprocesses which each takes 2.5 to 5 seconds and are parametrized. Those test are likely not platform dependant and could be marked "slow" and tested in only one matrix element, or only once per platform.

**Comment by Carreau** [comment]
@andy-sweet said in a meeting:

I guess most people know, but we can selectively run actions based on including/excluding paths: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths
