### ISSUE TITLE
Tracking possible demo datasets for napari

### ISSUE THREAD

**Issue by jni** [napari/napari#316]
Just saw this tweet announcing a human brain MRI at 100µm isotropic resolution. This could be a very cool dataset to use as a napari demo. I suggest we use this issue to keep track of datasets that we could put in napari once we have proper data downloading. Please just edit the checklist below to add your preferred demo data.

- [ ] 100µm resolution human brain: https://twitter.com/ComaRecoveryLab/status/1134436231775961088
- [ ] 10m resolution vegetation cover in Victoria: http://francois-petitjean.com/Research/MonashVegMap/info.php and https://labo.obs-mip.fr/multitemp/mapping-a-part-of-australia-at-10-m-resolution/
- [ ] correlative superres https://www.biorxiv.org/content/10.1101/773986v1.abstract
- [x] SARS-CoV2 in gut epithelium https://twitter.com/notjustmoore/status/1256232842755014656
- [ ] developing sea squirt https://www.nytimes.com/2020/07/09/science/sea-squirts-embryos.html
- [ ] mechanobiology of intestinal organoids https://twitter.com/XavierTrepat/status/1308026944349450241
- [ ] tracking of particles on astral microtubules ([paper](https://www.biorxiv.org/content/10.1101/2020.06.17.154260v1), [tweet (😍)](https://twitter.com/the_Node/status/1341050276011237379)), could make a really neat demo for the tracks layer.
- [ ] [Sentinel-2 1y Cloud optimised geotiff dataset](https://medium.com/sentinel-hub/digital-twin-sandbox-sentinel-2-collection-available-to-everyone-20f3b5de846e)
- [ ] Calcium imaging in the Drosophila ellipsoid body ([2013](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3830704/) and [2015](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4704792/))
- [ ] Janelia FlyLight data ([AWS](https://registry.opendata.aws/janelia-flylight/))
- [ ] Fruit Fly Brain Observatory (FFBO) ([tweet](https://twitter.com/FlyBrainObs/status/1369496338266750977))
- [ ] Janelia [Open Organelle datasets](https://openorganelle.janelia.org/)
- [ ] CZBiohub [Open Cell](https://opencell.czbiohub.org/about)
- [ ] [CoCo](https://cocodataset.org/#download) + [Voxel51 datasets](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html)
- [ ] @tlambert03's lattice light sheet dataset used in the dask application post https://www.ebi.ac.uk/biostudies/studies/S-BSST435?query=Talley%20lambert
- [ ] Merged magnetic resonance and light sheet microscopy of the whole mouse brain, PNAS 2023; https://doi.org/10.1073/pnas.2218617120 GitHub link: https://github.com/YuqiTianCIVM/MRH_LSM_registration Dataset in Neuroglancer h5 format: https://civmimagespace.civm.duhs.duke.edu/login.php/client/4
- [ ] mouse brain lipidome https://www.biorxiv.org/content/10.1101/2025.10.13.682018v1.full#sec-41
- [ ] Event-based camera data: https://www.biorxiv.org/content/10.1101/2023.01.11.523686v2

**Comment by jni** [comment]
Thank goodness for GitHub's automatic existing issue suggestions! I was just about to make an identical issue with item 2 from the above list. :sweat_smile:

**Comment by jni** [comment]
@sofroniewn I'm not sure whether this link belongs here, in tutorials, or in your image-demos repo, but I found these slides from Ryan Abernathey extremely interesting:

https://speakerdeck.com/rabernat/cloud-native-climate-data-with-zarr-and-xarray

Specifically, zarr and Google Cloud Storage appear to work very nicely together, so if we can get some of those demo datasets uploaded to GCS, we'd simultaneously get some napari demos with remote data *and* shareable big datasets.

**Comment by jni** [comment]
Just saw that a bunch of neuroscience datasets are now in s3 buckets:

https://neurodata.io/ocp/

Source: https://twitter.com/neuro_data/status/1204116321069195264

We should be able to load some of these into dask and visualise them with napari! Obviously, some will be more challenging than others, but as soon as we get lazy tiles working, we should be able to view any of these in napari... Which is so exciting!

**Comment by AMR-KELEG** [comment]
@jni Hi Juan,
This is Amr, the coach of team Bro-grammers (@din1881 and @DaliaAymanAmeen).
We are trying to download the dataset `100µm resolution human brain` but it's about 32GB. We have already sent a request to get a download link and are waiting for the reply.
Should the demo make use of such huge data-set?
Can we start with a couple of jpeg images like these ones (`https://histopath.nmr.mgh.harvard.edu/api/v1/region/155/640-880-1000-0-0-1`, `https://histopath.nmr.mgh.harvard.edu/api/v1/region/155/640-880-1001-0-0-1`)
We can download the 1700 snapshots and start visualizing them using napari.
What do you think?

Update: We have found a 2GB compressed file for the images from Axial view:
[Synthesized_FLASH25_100um_TIFF_Axial_Images.zip]( https://datadryad.org/stash/downloads/file_stream/223913)
Seems like a reasonable file to start with.
Thanks.

**Comment by jni** [comment]
@AMR-KELEG hello! The datasets above are only suggestions! The ideal case is to find a dataset that your team wants to explore and start looking at it with napari, then publishing notebooks with the exploration.

Note also that in many cases, using dask you can lazily load *remote* images as you look at them, rather than downloading a full dataset. This can be a bit slow and choppy but it'll work, and might be preferable to downloading a huge dataset. (In some cases, downloading the full dataset might be impossible, in fact.)

**Comment by sofroniewn** [comment]
@perlman checkout the list above for some cool datasets that we could try linking into - also feel free to add!!

**Comment by tlambert03** [comment]
Bonus if we can somehow turn it into a sample_hookspec plugin! 😃

**Comment by perlman** [comment]
@tlambert03 That's my goal. :) "Eric's first plugin".

**Comment by goanpeca** [comment]
Just wondering if there is an issue tracking any download utilities infrastructure needed for @jni 's comment

>once we have proper data downloading

**Comment by tlambert03** [comment]
I don't think there is actually.  Currently all downloading happens in wrapped libraries (scikit-image, dask, ome-zarr, etc...).  If someone opens anything with a remote protocol `napari https://...` all of that is left to plugins (and even the "builtin" plugin leaves it to downstream libraries).  Would be great to open an issue to discuss it

**Comment by goanpeca** [comment]
Yes please, could you open one to do some brainstorming 🧠 with any extra context you can think of.

Thanks !

**Comment by GenevieveBuckley** [comment]
Copying this comment over from the zulip discussion:

The rough wish list we currently have looks a bit like this:
- cells3d (from skimage)
- Talley's LLSM (or something similar, to use with all of Talley's demonstations)
- a tiny cell tracking dataset (ideally should contain at least one cell division)
- histology slide (largeish 2D tiled dataset, with mulitple resolution levels)
- a geodata example (maybe a Sentinel image tile, or something similar?)
- an astronomy example image?
- an already-segmented labels dataset (with corresponding image, probably)
- a surface dataset (mabye the stanford bunny or similar)

So, datasets for different scientific fields, datasets for different layer types, and both small & sort-of-big datasets (as in, just big enough to demonstrate concepts, given how long stuff takes to download)

**Comment by GenevieveBuckley** [comment]
For cell tracking, this dataset could be really interesting (there's a very speedy cell, and also a cell splitting in two). It's from this website: http://celltrackingchallenge.net/

> Human hepatocarcinoma-derived cells expressing the fusion protein YFP-TIA-1
>
> Dr. Alessia Ruggieri and Philipp Klein, Centre for Integrative Infectious Disease Research (CIID), University Hospital Heidelberg, Germany
>
> Training dataset: http://data.celltrackingchallenge.net/training-datasets/Fluo-C2DL-Huh7.zip (36 MB)
> Challenge dataset: http://data.celltrackingchallenge.net/challenge-datasets/Fluo-C2DL-Huh7.zip (36 MB)
> 
> Microscope: Nikon Eclipse Ti2
> Objective lens: CFI Plan Apo Lambda 20x/0.75
> Pixel size (microns): 0.65 x 0.65
> Time step (min): 15
> Additional information: Cell Host & Microbe, 2012

**Comment by GenevieveBuckley** [comment]
... and this 3D cell tracking dataset is gorgeous!

> C.elegans developing embryo
>
> Waterston Lab, University of Washington, Seattle, WA, USA
>
> Training dataset: http://data.celltrackingchallenge.net/training-datasets/Fluo-N3DH-CE.zip✱ (3.1 GB)
> Challenge dataset: http://data.celltrackingchallenge.net/challenge-datasets/Fluo-N3DH-CE.zip (1.7 GB)
>
> Microscope: Zeiss LSM 510 Meta
> Objective lens: Plan-Apochromat 63x/1.4 (oil)
> Voxel size (microns): 0.09 x 0.09 x 1.0
> Time step (min): 1 (1.5)
> Additional information: Nature Methods, 2008

**Comment by rbavery** [comment]
> a geodata example (maybe a Sentinel image tile, or something similar?)

@GenevieveBuckley I have radar images of oil slicks from Sentinel-1 if you'd like to use any as an example:

<img width="1440" alt="Screen Shot 2021-11-01 at 9 03 15 PM" src="https://user-images.githubusercontent.com/22258697/139785191-e5abf593-e523-44fd-a0cd-d24aef43681b.png">
<img width="1440" alt="Screen Shot 2021-11-01 at 9 03 00 PM" src="https://user-images.githubusercontent.com/22258697/139785207-28e9a870-8070-4f28-a935-ad548d365272.png">

**Comment by GenevieveBuckley** [comment]
@haesleinhuepf has a bunch of neat demo datasets available on zenodo for napari-pyclesperanto-assistant

https://zenodo.org/record/5090508#.YYDVeptxW-Z

There's some cool fly embryo datasets, and the [MRI of Robert's head](https://twitter.com/haesleinhuepf/status/1454716232712732679) is particularly impressive.

CalibZAPWfixed_000154_max.tif
md5:16f8b7efc838ae90e1aeff2806b17bca
9.2 MB
https://zenodo.org/record/5090508/files/CalibZAPWfixed_000154_max.tif?download=1

CLIJ_benchmarking_000350.raw.tif
md5:dd922189126289b3a374e88292f1f875
126.9 MB
https://zenodo.org/record/5090508/files/CLIJ_benchmarking_000350.raw.tif?download=1

EM_C_6_c0.tif
md5:6b346069c6620fd72ad90390e082a437
28.2 MB
https://zenodo.org/record/5090508/files/EM_C_6_c0.tif?download=1

Haase_MRT_tfl3d1.tif
md5:0253b9be403dd05cd38bea7cbcff00a5
98.3 MB
https://zenodo.org/record/5090508/files/Haase_MRT_tfl3d1.tif?download=1

tissue.tif
md5:87e28e362a132b598d6376d96f67d8bb
257.0 kB 	
https://zenodo.org/record/5090508/files/tissue.tif?download=1

tissue_measurements.tif
md5:d22e3c45e0a7654194c7119d70fe22a7
257.0 kB
https://zenodo.org/record/5090508/files/tissue_measurements.tif?download=1

**Comment by haesleinhuepf** [comment]
There is also some more developing Tribolium embryos, mouse brain slices and mouse colon volumes:

https://zenodo.org/record/4276076#.YYJKMWDMJaR

**Comment by haesleinhuepf** [comment]
Maybe, some classical example data sets from ImageJ's collection are also interesting:
https://imagej.nih.gov/ij/images/
https://imagej.net/images/

**Comment by jni** [comment]
@rbavery that's great (and terrible too :joy:). Is there a time series following the oil slick? That would be a fantastic demo.

**Comment by GenevieveBuckley** [comment]
@jni I notice that a lot of your links at the top of this issue are links to tweets, or links to say, a paywalled New York Times article. We'd need direct download links for the datasets in order to include any of those.

**Comment by rbavery** [comment]
@jni I don't have a time series at that location but I can see if the images acquired before and after this date still capture the evolution of this particular event. Because the revisit time is ~10 days we may or may not get anything but it could still be interesting to include a before and after scene.

**Comment by GenevieveBuckley** [comment]
@alisterburt I feel like it might be good to have a teeny-tiny cryo-EM dataset too. 

It might be hard to find something good in [EMPIAR](https://www.ebi.ac.uk/empiar/) - that tends to have buckets of huge amounts of data that may or may not be interesting. What we probably want is a very tiny cropped dataset that's already been processed and has an interesting structure in it. Maybe you have some ideas?

**Comment by alisterburt** [comment]
@GenevieveBuckley agreed! I'm planning to collate a few examples and get them on zenodo today 🙂

**Comment by GenevieveBuckley** [comment]
I assume the performance is better if you upload a zip file rather than the uncompressed dataset (haven't checked, but this seems a very safe assumption)

**Comment by alisterburt** [comment]
Small update, have some examples but hitting snags with permission to upload (not all are public) - please hold

**Comment by haesleinhuepf** [comment]
Hi all, 
I also just discovered a rich source for example data of beautiful microscopy data CC0 licensed:

https://scif.io/images/ 

🥳

**Comment by chili-chiu** [comment]
There are lots of great resources mentioned in this issue. I wonder if we can make them more visible to the community:
(1) Some as sample data plugins
(2) Others can be surfaced on napari.org with links and explanation of datasets (scientific domain, the type of image etc), perhaps a new page Usage > datasets (or some better name)?

**Comment by sofroniewn** [comment]
I think @neuromusic might have some ideas here for surfacing sample data plugins on napari hub

**Comment by alisterburt** [comment]
two cryo-ET datasets to add to the pile

https://zenodo.org/record/6504891 - deconvolved tomogram of HIV virus-like particles + annotations
https://zenodo.org/record/6504949 - denoised tomogram of a M. pneumonaie cell

**Comment by alisterburt** [comment]
@chili-chiu a master plugin included in core napari which surfaced data from a few different domains would be super cool in my opinion - very useful when running workshops for people in different scientific domains

**Comment by neuromusic** [comment]
> I think @neuromusic might have some ideas here for surfacing sample data plugins on napari hub

Indeed :D 

With npe2 support landing soon, users will be able to filter down to plugins that include sample data.

Later (perhaps later this year?) we might be able to parse the manifest files for sample datasets then add a "data" section to the napari hub, featuring datasets that are available through napari plugins.

**Comment by chili-chiu** [comment]
> @chili-chiu a master plugin included in core napari which surfaced data from a few different domains would be super cool in my opinion - very useful when running workshops for people in different scientific domains

Yes, that will be really nice! I like the list from @GenevieveBuckley, and in favor of smaller size images if possible, for demo purposes 😛  

What I'm wondering is how many of the resources gathered here can/should be turned into a demo data plugin, thus the second option of surfacing on napari.org as a lightweight alternative to have the rich resources mentioned, but might not fit the demo data plugin, more visible.

For some datasets, the source website may also include a lot of information that could be valuable. For example, https://scif.io/images/ has diverse file formats that could be tricky to implement and is a good source for testing other reader plugins 😆

**Comment by GenevieveBuckley** [comment]
TomoBank might also have some good example datasets. 

https://tomobank.readthedocs.io/en/latest/

> The X-ray Tomography Data Bank or TomoBank, provides a repository of experimental and simulated data sets with the aim to foster collaboration among computational scientists, beamline scientists and experimentalists, to accelerate the development of tomographic reconstruction and 3D visualization methods and to speed up their implementation in the various synchrotron facility data analysis software packages.


You do have to download them from Globus (which needs a login and imo is a bit flaky), but on the bright side at least some of these datsaets are stored as .h5 files.

**Comment by jni** [comment]
Another one:

https://github.com/Dey-Lab-Team/culture-collections#download-data

From the [paper](https://www.biorxiv.org/content/10.1101/2024.10.18.618984v1):

"Here, we use Ultrastructure Expansion Microscopy (U-ExM) to carry out high-resolution volumetric imaging of over 200 cultured planktonic eukaryotes across major lineages."

This one was shared by @guiwitz during one of the Eurasia meetings. There's some absolutely glorious data that might replace our home page movie one day.
