### ISSUE TITLE
deploy revised docs architecture using napari-sphinx-theme

### ISSUE THREAD

**Issue by neuromusic** [napari/napari#4151]
## 🧰 Task
Following up on #4047, we need to deploy the revised site.

We're aiming to complete this by

Steps to complete this task:

- [x] #4124 
- [x] #4147 
- [x] revert to "old" embedded Google Calendar (until react calendar is ready again)
- [x] implement new deployment workflow (@codemonkey800)
- [x] Create a new `gh-pages` branch in in napari
- [x] Configure `gh-pages` to be the source for branch in https://github.com/napari/napari/settings/pages
- [x] Disable the `gh-pages` for https://github.com/napari/napari.github.io
- [x] Add the CNAME to napari's `gh-pages` branch: https://github.com/napari/napari.github.io/blob/gh-pages/CNAME
- [x] Add Google calendar secrets to napari

**Comment by jni** [comment]
This is LIVE! :tada: :tada: :tada:
