### ISSUE TITLE
Saving and editing reader plugin preferences

### ISSUE THREAD

**Issue by junxini** [napari/napari#4613]
## 🚀 Feature
When opening an image format supported by napari natively or by an installed plugin, I want the option to save and edit preferences, so that I don't have to re-select every time

## Current behavior
(0.4.16) There’s existing work to improve the preference saving options in both the reader dialog and the preference dialogs. When there are multiple ways to open a file, users select which plugin they want to use and have the option to remember their preference so that the file will open automatically in the future. Edits to the plugin preferences can be made using the existing preference dialog (see #3799)

## Pitch

- [ ] 1. When plugin preference IS saved, the reader dialog currently appears if there’s an error. Add an alert to the user when saving a preference will override an existing one, both in the reader and preference dialogs

- [ ] 2. When plugin preference IS saved, provide option for user to force reader dialog to pop up (see [#4388](https://github.com/napari/napari/issues/4388))

- [x] 3. When there are 2 saved preferences that open a file (e.g., *.tiff vs myfolder/*.tiff), the more specific preference will override the generic preference (see comment under [#4459](https://github.com/napari/napari/pull/4459#issuecomment-1115407759))

- [ ] 4. Allow user to save plugin preferences for opening folders in the preference dialog (see [#4111](https://github.com/napari/napari/issues/4111))

- [ ] 5. Show which plugin is supporting the open file if not opened by napari natively by exposing the `layer.source` attribute in the GUI ([PR #4664](https://github.com/napari/napari/pull/4664))

## Additional context

This feature request is under epic https://github.com/napari/napari/issues/4611, in collaboration with @DragaDoncila, @chili-chiu, and @Lisa-CZI

**Comment by DragaDoncila** [comment]
I actually think everything here has been done 🎉 so I will close this now. If folks find any bugs with the features above, please open a new issue to track 🙏
