### ISSUE TITLE
Decision about ruff rules

### ISSUE THREAD

**Issue by Czaki** [napari/napari#5589]
## 🧰 Task

During adding ruff rules, I do not decide to enable some rules, as they are not compatible with the current codebase, and changes may be controversial. 

But enabling some of these rules may be useful in the future:

* [ ] [flake8-boolean-trap (`FBT`)](https://beta.ruff.rs/docs/rules/#flake8-boolean-trap-fbt) - block using of boolean args without the explicit name (`arg=True`). This should prevent common mistakes when using boolean variables. 
* [ ] [pep8-naming (`N`)](https://beta.ruff.rs/docs/rules/#pep8-naming-n) - enforce following PEP8 convention. May simplify reading code. 
* [ ] [flake8-errmsg (`EM`)](https://beta.ruff.rs/docs/rules/#flake8-errmsg-em) - after applying these changes the stack traces should be more readable. 
* [x] [flake8-print (`T20`)](https://beta.ruff.rs/docs/rules/#flake8-print-t20) - ban print, logging should be used instead. (WIP #6849)
* [x] [flake8-quotes (`Q`)](https://beta.ruff.rs/docs/rules/#flake8-quotes-q) - in this case the Rule Q000. I do not know why, but we do not have a consistent style, and it is explicitly disabled https://github.com/napari/napari/blob/58b76b668c0cead0782cff956e03010276213f6e/pyproject.toml#L31 (added by #6407)
* [ ] [flake8-type-checking (TCH)](https://beta.ruff.rs/docs/rules/#flake8-type-checking-tch) - enforce to import used only in type checking with `TYPE_CHECKING` guard - most important checks are currently disabled (`TCH001-3`)
* [ ] [flake8-use-pathlib (PTH)](https://beta.ruff.rs/docs/rules/#flake8-use-pathlib-pth) - switch from `os.path` to `pathlib`
* [ ] [flake8-unused-arguments (ARG)](https://beta.ruff.rs/docs/rules/#flake8-unused-arguments-arg) - ban usused args of functions. It could be nice from one side, from other side it may disable this in many places where functional API needs to be satisfied.
* [x] [flake8-slots](https://docs.astral.sh/ruff/rules/#flake8-slots-slot): ensure use of `__slots__` where useful (WIP: #6843)
* [x] [flake8-pytest-style](https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt): lots of small things with fixtures and asserts. (WIP: #6842)
* [ ] [flake8-gettext](https://docs.astral.sh/ruff/rules/#flake8-gettext-int): for translations use with fstrings. Not sure if we cover this with some custom check, cause this already passes on our codebase.
* [ ] [flake8-bandit](https://docs.astral.sh/ruff/rules/#flake8-bandit-s): security checks like running unsafe subprocesses and so on. Quite a few things to fix, but probably worth it for folks running napari on clusters and/or remotely.

Ideally, we would just check `ALL` and only add ignores to a few things so it's easier to keep up to date.

This issue will be updated with new PRs.

**Comment by aganders3** [comment]
I'm generally +1 on most of these.

I lean -1 on `flake8-errmsg` but it's not a strong opinion. I feel the benefit for tracebacks is arguable (e.g. it can help to see the variable name in an f-string) and I think it makes the _code_ look worse.

For quotes what is the difference between adding `flake8-quotes` vs. just changing the Black config?

**Comment by Czaki** [comment]
> For quotes what is the difference between adding `flake8-quotes` vs. just changing the Black config?

`flake8-quotes` allow to the configuration of different quotes for different cases. So if We select `"` everywhere then there will be no difference.

**Comment by kephale** [comment]
Looking over https://github.com/napari/napari/pull/5590/files, the changes the ruff rule enforcement makes seem pretty reasonable and I see some simplification happening, which is great. 

With respect to, `flake8-errmsg` I skimmed https://github.com/napari/napari/pull/5590/files and after a not-super-thorough check, I only saw a few places that it looks like this would have an impact. As a result, I'm fine with this being added in. I do agree with @aganders3 that the extra line of code it adds does not make the codebase look better, but if it really is only making changes in a few places, then it is probably worth it because of the benefit for end-users.

**Comment by Czaki** [comment]
Currently `flake8-errmsg` generates 46 errors:

```
examples/dask_nD_image.py:14:9: EM101 Exception must not use a string literal, assign to variable first
examples/dev/gui_notifications_threaded.py:18:22: EM101 Exception must not use a string literal, assign to variable first
examples/progress_bar_segmentation_.py:82:25: EM101 Exception must not use a string literal, assign to variable first
examples/surface_timeseries_.py:14:9: EM101 Exception must not use a string literal, assign to variable first
examples/xarray_nD_image_.py:14:9: EM101 Exception must not use a string literal, assign to variable first
examples/zarr_nD_image_.py:14:9: EM101 Exception must not use a string literal, assign to variable first
napari/_lazy.py:54:21: EM102 Exception must not use an f-string literal, assign to variable first
napari/_lazy.py:60:30: EM102 Exception must not use an f-string literal, assign to variable first
napari/_qt/_tests/test_qt_notifications.py:42:22: EM101 Exception must not use a string literal, assign to variable first
napari/_qt/dialogs/_tests/test_installer_process.py:89:34: EM101 Exception must not use a string literal, assign to variable first
napari/_qt/dialogs/qt_package_installer.py:116:30: EM102 Exception must not use an f-string literal, assign to variable first
napari/_qt/dialogs/qt_package_installer.py:235:26: EM101 Exception must not use a string literal, assign to variable first
napari/_qt/dialogs/qt_package_installer.py:390:26: EM102 Exception must not use an f-string literal, assign to variable first
napari/_qt/menus/_tests/test_file_menu.py:95:9: EM102 Exception must not use an f-string literal, assign to variable first
napari/_tests/test_cli.py:161:17: EM101 Exception must not use a string literal, assign to variable first
napari/_tests/test_view_layers.py:86:17: EM102 Exception must not use an f-string literal, assign to variable first
napari/benchmarks/benchmark_image_layer.py:63:39: EM101 Exception must not use a string literal, assign to variable first
napari/benchmarks/benchmark_labels_layer.py:74:39: EM101 Exception must not use a string literal, assign to variable first
napari/components/_layer_slicer.py:118:17: EM102 Exception must not use an f-string literal, assign to variable first
napari/components/_tests/test_layer_slicer.py:265:32: EM101 Exception must not use a string literal, assign to variable first
napari/components/_tests/test_layer_slicer.py:280:32: EM101 Exception must not use a string literal, assign to variable first
napari/components/_tests/test_layer_slicer.py:405:17: EM102 Exception must not use an f-string literal, assign to variable first
napari/layers/base/_base_constants.py:108:30: EM102 Exception must not use an f-string literal, assign to variable first
napari/layers/labels/labels.py:964:30: EM101 Exception must not use a string literal, assign to variable first
napari/layers/points/_tests/test_points_mouse_bindings.py:797:34: EM101 Exception must not use a string literal, assign to variable first
napari/layers/points/_tests/test_points_mouse_bindings.py:836:34: EM101 Exception must not use a string literal, assign to variable first
napari/layers/shapes/_tests/test_shapes_mouse_bindings.py:873:34: EM101 Exception must not use a string literal, assign to variable first
napari/layers/shapes/_tests/test_shapes_mouse_bindings.py:902:34: EM101 Exception must not use a string literal, assign to variable first
napari/layers/surface/surface.py:379:17: EM102 Exception must not use an f-string literal, assign to variable first
napari/layers/surface/surface.py:393:17: EM102 Exception must not use an f-string literal, assign to variable first
napari/layers/utils/interaction_box.py:117:26: EM101 Exception must not use a string literal, assign to variable first
napari/plugins/_tests/test_exceptions.py:28:17: EM101 Exception must not use a string literal, assign to variable first
napari/settings/_tests/test_migrations.py:69:26: EM101 Exception must not use a string literal, assign to variable first
napari/utils/_dtype.py:112:25: EM102 Exception must not use an f-string literal, assign to variable first
napari/utils/_proxies.py:103:17: EM101 Exception must not use a string literal, assign to variable first
napari/utils/_tests/test_notification_manager.py:68:39: EM101 Exception must not use a string literal, assign to variable first
napari/utils/_tests/test_notification_manager.py:118:39: EM101 Exception must not use a string literal, assign to variable first
napari/utils/events/_tests/test_evented_list.py:115:30: EM101 Exception must not use a string literal, assign to variable first
napari/utils/events/_tests/test_evented_list.py:173:30: EM101 Exception must not use a string literal, assign to variable first
napari/utils/events/containers/_dict.py:59:17: EM102 Exception must not use an f-string literal, assign to variable first
napari/utils/events/containers/_nested_list.py:190:38: EM102 Exception must not use an f-string literal, assign to variable first
napari/utils/events/containers/_nested_list.py:497:25: EM102 Exception must not use an f-string literal, assign to variable first
napari/utils/events/evented_model.py:145:21: EM102 Exception must not use an f-string literal, assign to variable first
napari/utils/io.py:76:26: EM102 Exception must not use an f-string literal, assign to variable first
napari/utils/perf/_stat.py:61:26: EM101 Exception must not use a string literal, assign to variable first
napari_builtins/io/_read.py:180:26: EM101 Exception must not use a string literal, assign to variable first
```

There is also `TRY003` rule that is much more strict https://beta.ruff.rs/docs/rules/#tryceratops-try (configuration option allows to set maximum string length.

**Comment by seankmartin** [comment]
I also like these rules in general! I think the traceback clarity benefit of the `flake8-errmsg` might be worth the code looking a little worse in places.

**Comment by brisvag** [comment]
I forgot about this tracking issue; I have a couple PRs following up on this:
- #6840 is adding these (relatively small)
	- "ASYNC", # flake8-async
    - "EXE", # flake8-executable
    - "FA", # flake8-future-annotations
    - "LOG", # flake8-logging
    - "T20", # flake8-print
- #6842 is adding pytest-style
- #6843 add `flake8-slots`

on top I would update the list in the OP as such:

* [ ] [flake8-boolean-trap (`FBT`)](https://beta.ruff.rs/docs/rules/#flake8-boolean-trap-fbt) - block using of boolean args without the explicit name (`arg=True`). This should prevent common mistakes when using boolean variables. 
* [ ] [pep8-naming (`N`)](https://beta.ruff.rs/docs/rules/#pep8-naming-n) - enforce following PEP8 convention. May simplify reading code. 
* [ ] [flake8-errmsg (`EM`)](https://beta.ruff.rs/docs/rules/#flake8-errmsg-em) - after applying these changes the stack traces should be more readable. 
* [ ] [flake8-print (`T20`)](https://beta.ruff.rs/docs/rules/#flake8-print-t20) - ban print, logging should be used instead. (WIP #6840)
* [x] [flake8-quotes (`Q`)](https://beta.ruff.rs/docs/rules/#flake8-quotes-q) - in this case the Rule Q000. I do not know why, but we do not have a consistent style, and it is explicitly disabled https://github.com/napari/napari/blob/58b76b668c0cead0782cff956e03010276213f6e/pyproject.toml#L31 (added by #6407)
* [x] [flake8-type-checking (TCH)](https://beta.ruff.rs/docs/rules/#flake8-type-checking-tch) - enforce to import used only in type checking with `TYPE_CHECKING` guard - most important checks are currently disabled (`TCH001-3`)
* [ ] [flake8-use-pathlib (PTH)](https://beta.ruff.rs/docs/rules/#flake8-use-pathlib-pth) - switch from `os.path` to `pathlib`
* [ ] [flake8-unused-arguments (ARG)](https://beta.ruff.rs/docs/rules/#flake8-unused-arguments-arg) - ban usused args of functions. It could be nice from one side, from other side it may disable this in many places where functional API needs to be satisfied.
* [ ] [flake8-slots](https://docs.astral.sh/ruff/rules/#flake8-slots-slot): ensure use of `__slots__` where useful (WIP: #6843)
* [ ] [flake8-pytest-style](https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt): lots of small things with fixtures and asserts. (WIP: #6842)
* [ ] [flake8-gettext](https://docs.astral.sh/ruff/rules/#flake8-gettext-int): for translations use with fstrings. Not sure if we cover this with some custom check, cause this already passes on our codebase.
* [ ] [flake8-bandit](https://docs.astral.sh/ruff/rules/#flake8-bandit-s): security checks like running unsafe subprocesses and so on. Quite a few things to fix, but probably worth it for folks running napari on clusters and/or remotely.

**Comment by TimMonko** [comment]
Hi everyone, just wondering where we are on this issue. Are we happy with the current ruff rules and therefore close this issue? Would we like to re-evaluate now a year later?

**Comment by Czaki** [comment]
Hm. I think it may be treated as resolved. We may want to revisit the list of rules and cheek if we want to add some new. But it may be out of the scope of this issue.
