### ISSUE TITLE
Layer groups tracking issue

### ISSUE THREAD

**Issue by jni** [napari/napari#5950]
- [ ] drop-in replacement of layerlist with nested layergroups (only organizational utility of layergroups)
- [ ] design inheritance/sharing system for attributes of layers that are children to the same group (adding function to layergroups)
- [ ] composite reader plugins (return multiple layers associated in groups)

Original issues:
- [ ] napari/napari#970
- [ ] napari/napari#2229

PR attempts: (😭)
- [ ] napari/napari#1502
- [ ] napari/napari#2261
- [ ] napari/napari#4018
- [ ] napari/napari#5132

**Comment by kephale** [comment]
Layer groupings were brought up in the context of the [Layer Controls re-design](https://github.com/napari/napari/issues/5358).

@jni has suggested considering a broader range of ideas for interacting with layer groupings than the traditional tree-view (e.g. Blender's [outliner](https://docs.blender.org/manual/en/latest/editors/outliner/introduction.html)), like graphs and views.

**Comment by kephale** [comment]
We had an interesting discussion about layer groups in [this community meeting](https://hackmd.io/BXWDZ3i8Q6OAEASrkaSNIQ#2023-09-13) [tag: @Czaki @melonora @seankmartin].

**Comment by kephale** [comment]
This is dated and not the type of scene graph/layer grouping we've been discussing, but might be useful as a reference: https://github.com/mfessenden/SceneGraph

**Comment by isabela-pf** [comment]
Heads up that I'm planning to look into layer groups work from a user experience and design perspective! I've been reading up on all the issues and PRs linked here, as well as the links they each hold. 

As this is the tracking issue I plan to update here sparingly and more on specific issues.
