### ISSUE TITLE
Contributable menus

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#6174]
This issue is intended to describe technical implementation details for [NAP-6](https://napari.org/dev/naps/6-contributable-menus.html) and be a 'meta-issue' for work that needs to be done.

### Implementation

- [ ] Add list of contributable menus to `napari/constants/_menus.py`, a warning for invalid IDs and new top level menus (`Layers`, `Acquisition`) and new submenu `File->I/O Utilities` as per [#5153](https://github.com/napari/napari/pull/5153/files/e55ed333866384d85a780b8c2ab1591fab460300#diff-4ab84b59ab3d5cadbcf97fb21bd6547982d5b444251fd627a0b50deb51bec83b)
- [ ] Add functionality for opening widgets from a menu item - ensuring we can provide objects required to build the widget via dependency injection in in-and-out
- [ ] Decide on exactly what types may be used as type hints for dependency injection in a plugin command function (these are the names that are declared in the the `app.injection_store.namespace`), and ensure we have providers for these types. Also document this.
- [ ] Ensure we use public-only object proxy for injected viewer (and other?) objects - see: https://github.com/napari/napari/pull/3736
- [ ] Implement processors for objects returned by a plugin command (e.g., adding layer to viewer) AND ensure they work both headless and with GUI
- [ ] Implement menu contribution interface that allows plugins to create and refer to new submenus. (Do we want to add plugin name to end of submenu's? This may be needed to avoid name clashes)
- [ ] Add icon/something to signal when a menu item is a widget, so users will know when clicking on something will open a widget vs run something.
- [ ] Implement `Action` `enablement`
- [ ] https://github.com/napari/napari/issues/6326
- [ ] https://github.com/napari/napari/issues/6224
- [ ] Add missing tests from https://github.com/napari/napari/pull/4847 e.g., I don't think `_when_group_order` is tested

### Documentation

- [ ] Document menu contribution guide in npe2 and expose menu contribution reference in npe2 so docs get built for them.
- [ ] Document `enablement` for contributions.
- [ ] Update cookie-cutter (and maybe demo tutorial) to add examples of menu contribution and action enablement.
- [ ] Update `docs/guides/contexts_expressions` now that expressions are implemented in app-model (ref: https://github.com/napari/napari/issues/4860#issuecomment-1586451648).
- [ ] Document context keys (`LayerList` and `Selection[LayerList]`) - note that Talley said : "I do have a plan for (auto)generating front facing docs using the descriptions in these ContextKey objects" (ref: https://github.com/napari/docs/issues/146).
        - Out of scope for this body of work but wanted to highlight this: https://github.com/napari/napari/issues/4919#issue-1333663176
- [ ] Document callback annotation and types processed by current processors (note we decided to only support injection of napari viewer, so docs of available providers probably not needed)
- [ ] Add documentation explaining how to use `superqt.fonticons` to declare icons (and figure out the best way for those icons to change colour with the theme).

### Discussion

- [ ] Should plugins be able to contribute to another plugins submenu? Note currently I think this can happen.
- [x] Going forward, do we want to support wrapper widget contributions (see: https://github.com/napari/npe2/pull/310) (I think no). Do we want to be backwards compatible and support wrapper contributions in the plugin menu only, or some alternate solution?

It was easy to and backwards compatible so we support all 3 'types' of widget contributions

- [x] Do we want to support `napari_viewer` param for widgets to request the viewer. This was added in #2080 and is documented in the [cookie cutter](https://github.com/napari/cookiecutter-napari-plugin/blob/6e1d851ad6a0e2b3a584366c4fdef3f3dcd433da/%7B%7Bcookiecutter.plugin_name%7D%7D/src/%7B%7Bcookiecutter.module_name%7D%7D/_widget.py#L21) and in [demo tutorial](https://github.com/napari/napari-workshop-template/blob/c03217fa7ca8822932d26d811fa6d5c2b2c69a29/napari-workshops/make_a_simple_plugin.md?plain=1#L231). Not sure how commonly this is used. Found https://github.com/napari/cookiecutter-napari-plugin/issues/69#issue-1078956774 which says that `napari.viewer.Viewer` should be preferred over `napari_vewer` but does not say why.

Supported.

- [ ] Currently the layer context menu id is `napari/layers/context`, we also plan to add a top level layer menubar with id `napari/layers`. This is not ideal as one would expect the former to be a submenu of the latter and both of these menus would be exposed as contributable. We should rename one, potentially `napari/layers/context` -> `napari/layerlist/context` which may cause some confusion but is better.
 
Some items have been copied from #4860

**Comment by lucyleeow** [comment]
Widget App-model migration needs to be general so widgets are able to be added to any menu, not just within the plugin menu. This will be implemented in #4991 (plugin menu migration) and form the basis of the widget aspect of contributable menus.

Currently there are 4 ways to define a widget:

1. Widget class that must be a subclass of `QtWidgets.QWidget` or `magicgui.widgets.Widget`
1. `magicgui.magic_factory` decorated function
2. Wrapper function that returns an instance of QtWidgets.QWidget (e.g., )
3. Arbitrary function, with `autogenerate` set to `true`

`WidgetContribution.get_callable` in npe2 will return the widget contribution and in the case of 4, changing it to a `magicgui.magic_factory` decorated function. Thus the possible outputs of `get_callable` that napari sees are 1 to 3.

After discussion with @DragaDoncila and @Czaki, we think we don't want to support 3 because it is difficult to type (both the wrapper, which will just be a normal function, and the return object, which could be many things) and is too flexible and difficult  maintain. To keep backwards compatibility, 3 will only be supported in the plugin menu.

To implement:

*Non-plugin menu items:*
*  create and register an `Action` for widget contributions. For 1 and 2, the callback should be a wrapper function that returns 1 and 2. 3 will not be supported
* define processors for each return type, that take the widget, wrap it in a dock widget and add to the viewer. The following 3 types will be supported : 

    * `magicgui.widgets.Widget` subclas
    * `QtWidgets.QWidget` subclass
    * `magicgui.widgets.Widget`
   
*Plugin menu items:*
Items 1 and 2 will be handled as above. For 3, (widget contribution that is just a wrapper function) the callback used to create the `Action` will add the processed widget to the viewer. No processor will be required in this case.

Please let me know of any mistakes/mis-undertandings @DragaDoncila @Czaki

**Comment by jni** [comment]
Brief notes from a meeting with me, @DragaDoncila, @lucyleeow:

- contributable "pure functions" can be either autogenerated into a widget by magicgui *or* they can be run directly based on the in-n-out context. Example: image math, "add two images together" — if two images are selected in the layer list, then we can just run it on those two images. Otherwise, we can autogenerate the widget to select the two images. Further, this same command could appear on both the layerlist context menu and in the menubar.
- Problem: in some situations, some functions might e.g. only take a single layer argument, but users have a single layer selected just because that's the default behaviour. So they might click on a menu item thinking that it is going to open a widget, but instead it just mutilates their layer.
- Additionally, it might be surprising if a menu item previously instantiated a widget, but now just runs because the user *happened* to have the right combination of layers selected. (On the other hand, this might be nice behaviour to have.)
- A standard Apple human interface guideline from menus (not sure how much other OSs or apps have copied this) is that if the menu item is going to open a new widget (rather than just run a thing), it should have an ellipsis (…) at the end.
- Similarly, currently, widgets that need particular layers will open just fine, but layer dropdowns won't be populated. Should these widgets instead be disabled until the correct combination of layers is present in the layer list? Consensus: no, plugin developers can decide on enablement disablement in the contribution.
- Backwards incompatible change: when functions are pure (meaning widgets can be autogenerated by magicgui) currently we make them *widget* contributions with `autogenerate: True`. If the same action is used for autogenerating widgets and for "just running" depending on context, then it should probably go under `commands: autogeneratable: True` or similar.

(To be continued.)

**Comment by lucyleeow** [comment]
close in favour of  #6174
