### ISSUE TITLE
napari/_qt/qt_event_loop.py has Deprecation Warning without version number.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#6251]
## 🧰 Task

In `napari/_qt/qt_event_loop.py` There is a warning without version number:

```
285-    warn(
286-        trans._(
287-            "\nThe 'gui_qt()' context manager is deprecated.\nIf you are running napari from a script, please use 'napari.run()' as follows:\n\n    import napari\n\n    viewer = napari.Viewer()  # no prior setup needed\n    # other code using the viewer...\n    napari.run()\n\nIn IPython or Jupyter, 'napari.run()' is not necessary. napari will automatically\nstart an interactive event loop for you: \n\n    import napari\n    viewer = napari.Viewer()  # that's it!\n",
288-            deferred=True,
289-        ),
290:        FutureWarning,
```

It would be nice to : 

 - [ ] find since when/which PR/Whihch napari version it has been there.
 - [ ] add the version number in the message, and 
 - [ ] potentially remove the deprecated functionality if we believe it's been long enough. 

All of this are issues that would be easy for new contributor.

**Comment by GenevieveBuckley** [comment]
The `gui_qt` context manager was deprecated in https://github.com/napari/napari/pull/2533 on April 14, 2021. 

That means the first napari release including a deprecation warning for `gui_qt` was [napari version 0.4.8](https://github.com/napari/napari/releases/tag/v0.4.8), released on May 19, 2021.

**Comment by GenevieveBuckley** [comment]
>  potentially remove the deprecated functionality if we believe it's been long enough.

I guess the real question is: when is "long enough"?

Personally, I'm in favour of removing it in the 0.5.0 release, since it's been deprecated for almost three years so far (and I imagine it will be longer than three years by the time the 0.5.0 release is done).
