### ISSUE TITLE
Investigate some potentially dead code.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#6258]
## 🧰 Task

All the following are code that appear to be dead, but is public and not in any `utils`, and seem to not have coverage. So might candidate for Deprecation/Deletion but further care need to be made as to _why_ it is dead. Is is useful for extension, or was it left there after last use by omission ? Assuming it should neither be deprecated nor removed, a test making sure those are covered would be good.

 - [ ] `napari/layers/base/base.py` , `click_plane_from_click_data` introduced in #3508
 - [ ] `napari/layers/base/base.py` , `data_to_world` method.  (there is a `_data_to_world` private attribute that is sometime used, maybe it was supposed to replace it) ?
 - [ ] `napari/layers/base/base.py`, `_extent_world`
 - [ ]  `napari/layers/base/base.py`, `_extent_world_aurgmented` only the Eponymous one LayerList seem to used and, there only in tests so potentially removable ? Maybe because `_get_extent_world(..., augmented=)` has an `augmented=` keyword.
 - [ ] `napari/layers/base/base.py`, `def bounding_box(..)`.
