### ISSUE TITLE
API notes for Labels layer (and beyond)

### ISSUE THREAD

**Issue by jni** [napari/napari#6491]
## 🧰 Task

Dealing with #6397 has been a game of whack-a-mole with the Labels layer, because it is a house of cards of hacks built upon hacks built upon my original hack/sin 😂 (#175), which was a way to commandeer the ImageNode machinery to display segmentations. As I review the various whack-a-mole PRs I am going to use this issue to gather all the thoughts for the API fixes that we need to make, and link to individual issues that may already exist.

- [ ] num_colors, colors, color_mode, _random_colormap, and _direct_colormap are all redundant with colormap. A colormap is a colormap is a colormap, and that should be the one API that controls how to match labels to colors. A colormap is a function that maps data to colors, which is what all of the above do. I think part of the reason they are so distinct is that they were each created independently at different times, and .colormap in particular was not usable for this purpose because we were saddled with inheritance from Image. Now that we have specialised shaders and specialised Colormap classes, we aren't so beholden to the Image API and we can engineer something that makes more sense. We can also allow selection of colormaps from named colormaps, e.g. 'lowdisc' for the default colormap, 'glasbey', (#454) etc.
- [ ] The above implies that all of the mapping from labels dtype to texture dtype needs to be the responsibility of the colormap, rather than being scattered all over the place as it is now.
- [ ] Having a precise colormap definition also allows us to e.g. allow plugins to create colormaps, which is probably a good idea for #1786, for example.
- [ ] (All of the above *kind of* imply that things like contrast limits and gamma belong in the colormap. At the very least, they should be parameters of the `map` function and the colormap instance can be a closure over those parameters.)
- [ ] Similarly, rather than force users to use `direct` mode to e.g. display features, we can use a `FeatureColormap()` that has a reference to the layer features and uses them to do the color mapping. (If we are worried about "class soup" for users — always a danger — we can have shorthand for this, e.g. `layer.colormap = 'feature::eccentricity::viridis'`, and `layer.colormap.contrast_limits = (0.5, 1)`.)
- [ ] `LabelColormap.use_selection` and `LabelColormap.selection` seem redundant — just make `LabelColormap.selection = None` to indicate `use_selection = False`?
- [ ] **Edit 1**: Having `None` as a key in the dictionary mapping labels to colors makes typing terrible, and makes it difficult to use accelerated frameworks such as Numba and Cython, which depend on strictly-typed classes and functions. We should instead use a defaultdict, or an attribute on the colormap class, or similar.

... I'll keep editing this issue as we keep encountering things to fix in the leadup to 0.4.19. But we can start discussing all of those points already. 😅 

CC @Czaki @andy-sweet @kevinyamauchi @jluethi

**Comment by andy-sweet** [comment]
Based a previous comment, we should also consider deprecating `LabelColormap.seed` which is not being used at the time of writing.

**Comment by aganders3** [comment]
> Edit 1: Having None as a key in the dictionary mapping labels to colors makes typing terrible, and makes it difficult to use accelerated frameworks such as Numba and Cython, which depend on strictly-typed classes and functions. We should instead use a defaultdict, or an attribute on the colormap class, or similar.

This is a good thought. I don't think Numba and Cython support `defaultdict` either, so maybe the extra attribute would be better. Can this all be done in a validator so users could supply however is most natural?

**Comment by Czaki** [comment]
Both support it, but it will make code painfull slow.
