### ISSUE TITLE
META Keybindings: app-model migration, plugin contribution, shortcut preferences

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#7059]
(Note this is a WIP and will be added to)

This is a meta issue to keep track of the body of work required to:

* migrate keybinding dispatch to app-model
* ensure npe2 plugin keybinding contributions can be correctly implemented
* enable keybindings to be editable in shortcut page of preferences dialog

Related work:

* migrate viewer and layer actions to app-model
* deprecate action manager

#### Keybinding and dispatch

- [x] https://github.com/pyapp-kit/app-model/issues/89 - this is essentially upstreaming https://github.com/napari/napari/pull/5604 to app-model, specifically see: https://github.com/napari/napari/pull/5604#issuecomment-1458558769. Talley seems supportive of this.
- [ ] https://github.com/pyapp-kit/app-model/issues/208
- [x] https://github.com/pyapp-kit/app-model/issues/207 - enable app-model keybinding registry to store source information
- [x] https://github.com/pyapp-kit/app-model/issues/206 - filter certain key codes and key combos. #6204 did this in napari but potentially this could be upstreamed
- [ ] Improve `KeyBindingRegistry.get_keybinding` to implement deal with `when`, `source` (and maybe `weight`, depending on what is decided in https://github.com/napari/napari/issues/7056). (depends on https://github.com/pyapp-kit/app-model/issues/177)
   - [ ] Handle key sequence conflicts - depends on #7056
- [ ] Dispatcher implementation - some should be upstreamed to app-model (https://github.com/pyapp-kit/app-model/issues/177#issuecomment-1979973730), but depends on what we decide in https://github.com/napari/napari/issues/7056

#### Viewer/layer actions and action manager

- [ ] Migrate viewer/layer actions to action manager - https://github.com/napari/napari/issues/7058 (depends on keybinding and dispatch being handled first, as these action shortcuts need to be user editable)
- [ ] https://github.com/napari/napari/issues/5999
- [ ] https://github.com/napari/napari/issues/5196 - deprecate action manager

#### Shortcut GUI

- [ ] Implement shortcuts to be editable via the preference dialog and update shortcuts appropriately
- [x] https://github.com/napari/napari/issues/5316

Supercedes https://github.com/napari/napari/issues/5874

Post NAP-7:

* #7246

cc @DragaDoncila @jni @dalthviz

**Comment by jni** [comment]
Worth checking whether this is fixed already or in the course of the work described here: #2799
