### ISSUE TITLE
big data + pyramid + contrast limits meta issue

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#736]
## 🐛 Bug
We have a number of open issues right now related to big data + pyramid + contrast limits calculations, we've struggled with our api here for a while and it's clearly a major driver of current bug reports. I'm going collect references to all the issues below and I'd like us to spend a little time thinking about what the best overall solution is

- [x] #624 #570 contrast limits and range guessing
- [x] #691 integer overflow in `is_pyramid` check, solution in progress #692 
- [x] #699 and #710 - call to `is_pyramid` forces zarr decompression, shouldn't call when `is_pyramid=False`
- [ ] #718 - request for better dask caching
- [x] #731 - big 3D data failed because `contrast_limits` not provided
- [x] #733 - possible duplicate of #699 and #733

Looking over this is seems that we should only call `is_pyramid` if the `is_pyramid=None` keyword is None (I might also rename the function as it is confusing to share names like this). I will make this PR right now.

We should also do better is `contrast_limits` is not provided.

**Comment by jni** [comment]
Thanks @sofroniewn! This has been causing me some anguish but I haven't found a moment to work on it. imho another tweak for the pyramid checking code is checking `hasattr(data, shape)`. If it has a shape, it must be regular and cannot be a pyramid. That should allow things to work with `is_pyramid=None`.

**Comment by jni** [comment]
On the plus side, it's very cool that so many people are using napari to look at big microscopy data!

**Comment by sofroniewn** [comment]
Unfortunately @jni we did have someone pass pyramid data as a 1-d numpy array with dtype object - see one of our old issues

**Comment by sofroniewn** [comment]
I am working on a PR adding unit tests with the timing like you did for the your recent dask uint8 PR

**Comment by jni** [comment]
@sofroniewn 

> Unfortunately @jni we did have someone pass pyramid data as a 1-d numpy array with dtype object - see one of our old issues

Ach! Users have such a way to find bugs. 😂 

How about:

`hasattr(data, 'shape') and hasattr(data, 'dtype') and data.dtype != 'object':`

?

**Comment by sofroniewn** [comment]
@jni checkout my solution here - https://github.com/napari/napari/pull/737#issuecomment-558416914

**Comment by sofroniewn** [comment]
Note also discussions in this issue - https://forum.image.sc/t/efficiently-open-qptiff-images-with-napari/33237/4?u=sofroniewn

> I first tried to define the contrast_limits, it does not change. I then tried is_pyramid=True and that makes a huge change (just a few seconds), Napari was effectively computing the pyramid levels, which is not necessary as they are already in the qptiff file.

**Comment by sofroniewn** [comment]
I'm going to close this now as it seems like the `contrast_limits` issues have been fixed and the https://github.com/napari/napari/blob/dec5b9965d4a3fcea2d8314064465af14a97fec7/napari/layers/layer_utils.py#L25-L65
function doesn't take too long if big data is provided - both zarr and dask - see https://github.com/napari/napari/blob/dec5b9965d4a3fcea2d8314064465af14a97fec7/napari/layers/image/_tests/test_big_image_timing.py#L14-L25

If anyone is continuing to have to pass `contrast_limits` in order to avoid expensive computations can they please open a fresh issue with a minimal example so we can make sure that isn't still happening for people. You might still need to pass the `is_pyramid=False` or `is_pyramid=True` depending on your circumstances.
