### ISSUE TITLE
Refactor Points data model

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#858]
## 🚀 Feature
This issue proposes to allow the user to store point metadata (`Points` layer) and allow setting of point properties as a function of the point metadata. Additionally, this issue explores the possibility of combining the `Points` and `Text` layers.

**Definitions**

For the purpose of this issue, I will use the following definitions:

- _point annotions_: metadata associated with each point. These are numbers or strings that describe each point and are set by the user. Each point can have multiple annotations. Some examples of possible annotations: class labels or descriptions of the points.
- _point properties_: display attributes of each point (e.g., `face_color`, `size`, and `edge_color`) that get passed to the vispy `Markers` node. 

## Motivation 

This proposal draws from the following discussions:

- #651 : @adamltyson proposed to add a class label to points
- #600 : @jni proposed to store the point properties in a `DataFrame` and combine `Points` and `Text` into a single layer (both toggleable)

### Approach
**Store point annotations in a `DataFrame`**

As proposed by @jni in #600, the point annotations  will be stored a `DataFrame` (`Points.annotations`). Properties can be definied upon instantiation of the layer using keyword arguments. All keyword arguments outside of the defined parameters will be captured  (with the `**kwargs` syntax) and used to instantiate the `Points.annotations` `DataFrame`.

```python
with napari.gui_qt():
    # create the viewer with an image layer
    viewer = napari.view_image(rgb2gray(data.astronaut()))
    
    # create the point data
    points = np.array([[100, 100], [200, 200], [333, 111]])
    size = np.array([10, 20, 20])
    
    # associate a class with each point
    point_classes = ['type A', 'type B', 'type A']
    
    points_layer = viewer.add_points(points, size=size, point_class=point_classes)
    
```
If no point annotations are provided upon layer creation, `Points.annotations` is instantiated as an empty `DataFrame` with an index corresponding with the indices of the points.

The point annotations can be added, modified, and deleted using standard `DataFrame` syntax. For example, we can add a new column (annotation) as follows:

```python
points_layer.annotations['gene_target'] = ['ACTB', 'GAPDH', 'ACTB]

```

**Setting Point properties**

Currently there are two types of point properties: (1) uniform properties, which have to be constant across the node and (2) per-point properties that can be set on a per-point basis.

Uniform properties (`symbol`, `edge_width`) will be set via our current setter methods (e.g., `Points.symbol = 'ring'`)

Per-point properties (`size`, `edge_color`, `face_color`) can either be set with values as they currently are (e.g., `Points.edge_color = [1, 1, 1, 1]`) or set as a function of one of the columns in the `Points.annotations` `DataFrame`. To accomodate setting point properties with columns of the `Points.annotations` `DataFrame`, I propose that we allow the point property setter methods to accept a tuple containing the string name of the column to use and an optional colormap (with a sensible default). The API would then look like: 

```python
# set all the same
points_layer.edge_color = [1, 1, 1, 1]

# give each point a different edge color
points_layer.edge_color = [
	[1, 0, 0, 1],
	[0, 0, 1, 1],
	[0, 1, 0, 1]
]

# set the edge color by the point_class with default cmap
points_layer.edge_color = ('point_class',)

# set the edge color by the point_class with a specified cmap
points_layer.edge_color = ('point_class', 'favorite_cmap')

```

**Data view**

We will move slicing of in-view point properties to the model (previously this was done in the vispy file). Doing so will both improve view-model separation and make it easier to write unittests. This will introduce the following properties (name suggestions welcome!):

- `Points._edge_colors_view`
- `Points._face_colors_view`
- `Points._sizes_view`
- `Points._annotations_view`

**Integrating Text**

Given that text and points share a data model (coordinates with annotations) and there will likely be use cases that require both text and points, it would be nice to integrate text display with the `Points` layer. Doing so would reduce the amount of code dupication between the two layer types Also, they are both representations of a set of coordinates, so thematically, it makes sense to combine them. However, there are two potential issues that I think would be useful to discuss:

- Adding text visuals requires adding extra properties for specifying how the text is displayed (e.g., font size and color) that would not be used when the user does not require text display. We can make all of the properties optional with sensible defaults, but it does roughly double the number of potential input arguments for creating a new `Points` layer and adds to the number of layer properties.
- Some of the interactions (e.g., highighting and selection) would require extra logic to change the behavior depending on the display state (points on/off and text on/off). This would not be too difficult to implement, but it does add to the bloat of the layer. 

Overall, I am in favor of adding text display to the `Points` layer because I think the two potential concerns above won't adversely affect the experience of the users and I think there are use cases where displaying points and text together would be nice (e.g., describing features in an image).

### Implementation plan
Following #782 landing, we will make the following PRs

- [x] Store point properties in a `DataFrame`
    - point properties in `DataFrame`
    - move point property view slicing to `Points` model
- [x] Allow properties to be set as a function of other annotations (similar to setting marker color as a function of a parameter in `plt.scatter`)
    - add util functions to determine if the property should be set by the provided value or apply a color cycle to a different property.
- [x] Integrate `Text` visual into `Points` layer
    - add hitbox and highlight box calculation for text visuals into `Points`
    - add logic to `vispy_points_layer.py` to add a `Text` node when annotations are turned on.

## Alternatives
We could consider including both the point properties and annotations in a single `DataFrame`. While this would be very convenient for slicing the in-view data and we could put all of the properties and annotations in a single class property, the `DataFrame` isn't really designed to hold array data.

If we are not in favor of integrating text display into `Points` and add a `Text` layer (clean up and merge #600).

An additional alternative to integrating text display into create atomic layer elements and then combine them via composition. In this scheme, we would have a `Points` element and a `Text` element that comprise a model and view (as our current layer) and then we would have an `Annotation` layer that joins and controls the `Points` and `Text` elements (i.e., this would behave more like a model-view-controller). This is a pretty substantial paradigm shift, so if we are interested in exploring this concept, I think we should do so after implemented the proposed integration approach (or wherever we land on the issue).

**Comment by jni** [comment]
@kevinyamauchi thanks! Very thorough! I can't do a full review immediately but I have some preliminary comments:

> We could consider including both the point properties and annotations in a single DataFrame. While this would be very convenient for slicing the in-view data and we could put all of the properties and annotations in a single class property, the DataFrame isn't really designed to hold array data.

I'm actually inclined to deprecate directly setting face color and edge color as anything *other* than a colormapped property *or* a single color. That is, if you wanted three colors of points, you would set face_color=[0, 0, 1, 1, 2, 1, 1, 2, 0, 1...] and if you wanted different colors you would change face_colormap/cycle.

> `# set the edge color by the point_class with a specified cmap`
> `points_layer.edge_color = ('point_class', 'favorite_cmap')`

I would set `edge_color` to be an annotation column name and separately set `edge_colormap`.

> with the **kwargs syntax

I don't love this and would prefer having `annotations={'colname': col, 'colname2': col2}`, ie the "packed" version of `**kwargs`. The converse makes static analysis much more difficult, and it makes it impossible to e.g. have a column called "edge_color" or "data" or any of a number of other possible name clashes.

> Data view

This relates to the world-slice coordinate system etc. This is the "instantiation" bit there. Part of the reason I like supporting only annotations is that it simplifies this a lot: only the data (coordinates) and attributes need to be updated. The converse is a huge pain!

Ok that's my input for now... Thanks again for creating this issue!

**Comment by kevinyamauchi** [comment]
Thanks for the quick feedback, @jni! I think you make some great points.

> I don't love this and would prefer having annotations={'colname': col, 'colname2': col2}, ie the "packed" version of **kwargs. The converse makes static analysis much more difficult, and it makes it impossible to e.g. have a column called "edge_color" or "data" or any of a number of other possible name clashes.

That works for me. I think that makes it more clear that the `annotations` are all grouped together.

> I'm actually inclined to deprecate directly setting face color and edge color as anything other than a colormapped property or a single color. That is, if you wanted three colors of points, you would set face_color=[0, 0, 1, 1, 2, 1, 1, 2, 0, 1...] and if you wanted different colors you would change face_colormap/cycle.

Interesting, I think I like this idea. To make sure we're on the same page, I've mocked out your proposed API as I understand it below. Is this what you have in mind?

```python

with napari.gui_qt():
    # create the viewer with an image layer
    viewer = napari.view_image(rgb2gray(data.astronaut()))
    
    # create the point data
    points = np.array([[100, 100], [200, 200], [333, 111]])
    size = np.array([10, 20, 20])
    
    # annotate each point with a class
    annotations={'point_class': ['type A', 'type B', 'type A']}
    
    points_layer = viewer.add_points(points, size=size, annotations=annotations)

    # we can add columns to the annotations DataFrame with standard DataFrame syntax
    points_layer.annotations['gene_target'] = ['ACTB', 'GAPDH', 'ACTB]

    # to set all points to the same edge_colors we can use a color name or RGBA tuple
    points_layer.edge_colors = 'red'
    points_layer.edge_colors = [1, 0, 0, 1]

    # we can also set the edge colors on a per-point basis using a color map and column name
    points_layer.edge_color_map = 'fave_cmap'
    points_layer.edge_color = 'point_class'

```

**Comment by HagaiHargil** [comment]
Interesting discussion, a couple of comments:

1. What about other layers such as `Shapes` and `Vectors` which can contain colors on a per-item basis? I'm guessing you'd want to change their color handling as well, to fit the `Points` one. #782 doesn't deal with these other layers as well, BTW.

2. Following  #686 `face_color` and `edge_color` are now `current_X_color`, which better conveys their use. IMHO they shouldn't be settable in the sense described above - i.e. they should internally just hold the index to the currently chosen color in `edge_colors` and `face_colors`, and when users wish to change the chosen color programmatically they can only supply a list of indices to change the current selection, they can't change the chosen color directly. Instead, they'll have to write `viewer.face_colors[viewer.current_face_color] = 'red'`.

3. If you want to store the properties and annotations in a single dataframe you can instead use a `xarray.DataArray` or `xarray.Dataset`. It can also be transparent to the users, I think, if you're (rightly) afraid that not many people know how to use these.

**Comment by kevinyamauchi** [comment]
Hey, @HagaiHargil ! Thanks for the comments.

> What about other layers such as Shapes and Vectors which can contain colors on a per-item basis? I'm guessing you'd want to change their color handling as well, to fit the Points one. #782 doesn't deal with these other layers as well, BTW.

I agree that we should also update the `Shapes` and `Vectors` layers to match the `Points` layer color property setting if we like the behavior. I just thought it would be easier to start by experimenting on a single layer first (while keeping in mind how it generalizes).

> Following #686 face_color and edge_color are now current_X_color, which better conveys their use. IMHO they shouldn't be settable in the sense described above - i.e. they should internally just hold the index to the currently chosen color in edge_colors and face_colors, and when users wish to change the chosen color programmatically they can only supply a list of indices to change the current selection, they can't change the chosen color directly. Instead, they'll have to write viewer.face_colors[viewer.current_face_color] = 'red'. 

Thanks for catching that, there is a typo in my example above (`points_layer.edge_color` should have been `points_layer.edge_colors`). I've updated the comment. Your comment made me realize that perhaps we need to think a bit more about how the colormap is stored (e.g., #862) users will likely want to be able to swap colors in the colormaps on the fly.

> If you want to store the properties and annotations in a single dataframe you can instead use a xarray.DataArray or xarray.Dataset. It can also be transparent to the users, I think, if you're (rightly) afraid that not many people know how to use these.

As you guessed, I am a bit weary of using `xarray.DataArray` to hold the data model due to how challenging it can be to interact with it. I think you raise a good point that if a `DataArray` is the best from a data model perspective, we can "hide" it from the user via API design. I think the current proposal is contains the minimal features of the `DataArray` (coordinates + attributes) without some of the more confusing aspects (e.g., slicing by different coords/indices). However, I am definitely up for discussion if there reasons we should more carefully consider adopting the `DataArray`!

**Comment by HagaiHargil** [comment]
Regarding `xarray` - my thought was that it might be simpler to hold everything in a single table, but I guess that we should first have a (semi-) working prototype with the DataFrames and then see if it can (and should) be changed.

**Comment by sofroniewn** [comment]
This is a great write-up @kevinyamauchi 

One question is if we go with the `DataFrame` approach do we now depend on pandas, and do we now use pandas objects internally? Do we accept pandas objects into our API (either required or optional)? I saw the example above you can pass a dictionary. I'm a little wary of the adding lots of pandas - and certainly don't want to force people into pandas. There are times when pandas and arrays behave weird together - like our `Nx4` array representation of #782. 

> I'm actually inclined to deprecate directly setting face color and edge color as anything other than a colormapped property or a single color. 

I'm not so sure about this, I think there are many times when you know the exact colors, list of colors you want, but I'm open to it. I still think getting #782 first in is good, even if we then revisit

**Comment by jni** [comment]
> One question is if we go with the DataFrame approach do we now depend on pandas, and do we now use pandas objects internally?

Yeah, to be honest, I don't know. If we are only using it for subsetting etc, then it possibly doesn't make sense, and we can keep a DF-compatible data structure (dict of arrays). (And we convert an input DF to that format.) If we find we need more advanced features (e.g. groupby), then we should strongly consider depending on it.

> I think there are many times when you know the exact colors, list of colors you want,

Yes, this is fixed with a color cycle:

```python
viewer.add_points(
    coords,
    annotations={'class': [0, 1, 1, 2, 0, 0, 1]},
    face_color='class',
    color_cycle=['cyan', 'magenta', 'yellow']
)
```

We would use color maps for ordinal/continuous variables, color cycles for categorical variables.

**Comment by sofroniewn** [comment]
> Yes, this is fixed with a color cycle:

That is quite nice!

>  If we are only using it for subsetting etc, then it possibly doesn't make sense, and we can keep a DF-compatible data structure (dict of arrays). (And we convert an input DF to that format.) If we find we need more advanced features (e.g. groupby), then we should strongly consider depending on it.

Hmm yeah, we'll have to see how it goes, I'd prefer us to avoid it as much as reasonably possible, maybe in a first pass, but if we find ourselves needing it / reimplementing parts of it then we should depend on pandas

**Comment by kevinyamauchi** [comment]
@jni and @sofroniewn , I think you make good points with regards to being cautious about adding a `pandas` dependency. I agree that we don't want our users to have to be familiar with the `pandas` API and ideally the `napari` model has as few dependencies as possible.

I had originally considered a dictionary of arrays, but I thought it might be nice to be able to group annotations (e.g., groupby or hierarchal index). However, based on the feedback and mocking out the API, it doesn't seem like we will use those features in the near future. Therefore, I agree we should proceed with storing the annotations in a dictionary of arrays (i.e., no `pandas` dependency for now). If we are careful with the implementation, changing to a `DataFrame` in the future shouldn't be too difficult.

**Colormap/colorcycle API**
I like the idea to support both colormaps and color cycles for representing continuous and discrete annotations, respectively. Ideally, I would like each per-point property (e.g., `face_color` and `edge_color`) to have their own colormap/color cycle. Also, I think it would be nice if the same property could accept both color maps and color cycles so we don't have two color representation properties (e.g., `edge_cmap` and `edge_color_cycle`). It looks like [seaborn uses "palette"](https://seaborn.pydata.org/tutorial/color_palettes.html). Perhaps we could do the same here (e.g., `edge_color_palette`)? 

**Getting started**
I think the ideas around this refactor are starting to gel to the point that it's worth taking a stab at the implementation to get feedback. It looks like #782 is getting really close, so I can get started on this once it is merged.

**Comment by jni** [comment]
I initially like the idea of the `palette` unified API, but I can spot some issues with it. For example, suppose you are displaying points, and you switch from using `'predicted label'` as the class to `z-score` or `PCA1`, then you will also need to switch from using a cycle to using a colormap. (The converse is not true because it is trivial to make a cycle from a colormap. But the other way is much harder and you would rarely want to do it e.g. with interpolation.) If you make these switches a few times, it might be much better to "save" the continuous colormap and the discrete color cycle separately...

One solution to this is to somehow detect whether the input to `palette` is a colormap or a color cycle, and then save the two in different internal variables, which get used depending on whether the values are continuous or categorical.

I'm leaning towards different variables (to limit magic), but feel free to implement either solution and we can see what it looks like!

**Comment by sofroniewn** [comment]
Looking over the proposed API again it seems very similar to both the seaborn and bokeh approach - which I think is a good things, as converge here probably means good API design. Both these approaches allow for a combination of dataframe + vectors to be used for setting properties.

I'd still appreciate an explicit work through of the use-case in #651 in the new proposed scheme (just from an API / function call perspective) as I think that will keep us on track to delivering a real needed improvement.

I've put a few notes below on Seaborn and Bokeh for those not familiar with their APIs

### Seaborn
In seaborn our `annotations` object is called `data` which is a

> data : DataFrame
>
> Tidy (“long-form”) dataframe where each column is a variable and each row is an observation.

and keyword arguments are as follows:

> size : name of variables in data or vector data, optional
> hue : name of variables in data or vector data, optional

see here - https://seaborn.pydata.org/generated/seaborn.lineplot.html#seaborn.lineplot

### Bokeh

In Bokeh our `annotations` object is a `source` which is a `ColumnDataSource` which can easily be created from a pandas dataframe like above - see here https://docs.bokeh.org/en/latest/docs/user_guide/data.html

**Comment by kevinyamauchi** [comment]
Great point, @sofroniewn . I've collected what I think are the key descriptors of the use case from #651 below.

> Assuming there is an NxD points array, I would like to be able to pass an Nx1 classes array to viewer.add_points, viewer.add_points(points, classes=classes). These would appear separated in the GUI, perhaps as an expandable list within a single Points section.
>
> When selecting a point, there would be an additional option to convert to class X, and ideally a keyboard shortcut to the number of that class.
>
> Even more ideally, the arguments to viewer.add_points should accept lists of length N (or Nx1 arrays) so we could use viewer.add_points(points, classes=classes, names=["Cell type 1", "Cell type 2", "Cell type 3"]).

> ...the key would be to allow users to easily switch the labels (whatever they may be). Think curating 10,000 data points for a deep learning workflow.

> for my use case, the label wouldn't need to be displayed next to the point, but there would need to be some way of telling what class each point was at a glance (e.g. color coding). Then the points which were "incorrect" could be moved, or have their class changed etc

Based on that, I think the we would do the following using the proposed API. This example would create a `napari` viewer with an image and points layers. The points would be colored green or magenta based on their annotated 'cell_type'. If the user selects some points and presses 'b', those points will be converted to cell type B. @adamltyson, sorry it's taken a bit of time, but would this meet your needs? Are there things you would change/improve with regards to the API?

```python
with napari.gui_qt():
    # create the viewer with an image layer
    viewer = napari.view_image(rgb2gray(data.astronaut()))
    
    # create the point data
    coords = np.array([[100, 100], [200, 200], [333, 111]])
    
    # annotate each point with a class
    annotations = {'cell_type': np.array(['type A', 'type B', 'type A'])}
    color_cycle = ['magenta', 'green']
    points_layer = viewer.add_points(
                                    coords, 
                                    annotations=annotations,
                                    face_color='cell_type',
                                    face_color_palette=color_cycle
    )

    # create a function to convert the selected point to type B
    @viewer.bind_key('b')
    def conv_to_b(viewer):
        selected_points = viewer.layers[1].selected_data
        if selected_points:
            viewer.layers[1].annotations['cell_type'][selected_points] = 'type B'

```

**Comment by adamltyson** [comment]
Hi @kevinyamauchi, no problem, thanks for working on this.

This is exactly what I had in mind. From a user point of view, the API looks very simple and flexible. I like that I could (for example), in the case of a binary label, easily change the function to just swap labels.

It's a different issue, but is it possible to add something like a summary box into the napari viewer? Something like:

***********
**Cell annotator**
There are `X` type A cells and `Y` type B cells.
Select points and press "c" to switch labels
************

Either way, for me this would completely resolve #651 

Thanks again!

**Comment by sofroniewn** [comment]
That's great that you like the API @adamltyson! 

I think functionality like your cell annotator box we'd leave to a plugin developer who wanted to make a cell annotation tool with a lot of customized convenience functionality, including custom keybindings and custom Qt displays like that summary box. We want to make sure that all the basic functionality for such a plugin is provided by the core of napari

**Comment by kevinyamauchi** [comment]
Thanks for the feedback, @adamltyson !

As @sofroniewn mentioned, we do not currently have a way to add a "summary box" type of UI element through the public API. However, we are currently discussing how best to implement plugins and I think use cases really help ground the discussion. It sounds like the cell annotator you are developing could work well as a plugin. If you have time, it would be great if you could make an issue describing your use case (sorry if you already have and I missed it)!

In case it is useful, I've listed/linked a couple of somewhat-related things that may be of interest.

- We have started discussing how best to incorporate simple plots (e.g., for summary data) into `napari`. If you have any thoughts, suggestions, or use cases, feel free to weigh in (#823)!
- We do have keybindings summary UI (press alt + cmd + / on Mac OS to open) that lists the current keybindings and their descriptions. When you add your keybinding, if you provide a docstring in the function definition, it will be displayed there. There is one small bug at the moment that you need to "refresh" the element after adding a keybinding by changing which layer is "active" in the GUI (i.e., change which layer is selected in the layer list).

![Screen Shot 2020-01-17 at 7 24 01 AM](https://user-images.githubusercontent.com/1120672/72624931-a175fe00-38fc-11ea-8011-24cabb040e3d.png)

**Comment by adamltyson** [comment]
Thanks for your feedback. Our use case is basically this issue. We have some software in the lab for detecting cells in whole-brain images, and these detected cells are refined using a DNN ([software](https://github.com/SainsburyWellcomeCentre/cellfinder)). We have a custom FIJI plugin that loads the results of this pipeline, and the classification (cell/artifact) can be refined to generate training data. I'm hoping to replace this functionality with napari (which is already used for all data viewing).

I'll hold off with the issue, because I'm not sure what functionality I need, whether I just want a help box for this annotation, or whether to work towards a full graphical front end for our software.

Thanks for the tips though, very helpful.

**Comment by kevinyamauchi** [comment]
Sounds good, @adamltyson! I’ll get started on this on Monday.

**Comment by kevinyamauchi** [comment]
I just merged the first PR introducing point properties and the ability to set colors using the point properties (#895). @adamltyson, I included the example (`examples/add_points_with_properties.py`) that you checked out earlier, but there are some syntax changes. Let me know if you have any questions or run into any issues!

**Moving point display property slicing into the model**
Currently, some of the in view point display properties (e.g., face color, edge_color) are sliced in the view (see [here](https://github.com/napari/napari/blob/4414d284461b3d62b688591c97ed84a0d525552c/napari/_vispy/vispy_points_layer.py#L54)). As I mentioned above, I would like to move that into the model. We already doing so for sizes and the data and it will make testing that much easier. I propose we add properties for the in view face_color and edge_color that return the in view face_color. Something like:

```python

@property
def _face_color_view(self):
    """Returns the face color of the points in the currently viewed slice"""
    return self._face_color[_self.indices_view]

```
How does that sound? I would also be fine with a regular method that does the same (e.g., `Points.get_face_color_view()`). Also, I am not attached to the name - I was just matching the naming scheme for the analogous data and size properties.  If you all like that pattern, I can propagate it to the data and sizes view as well (currently the in view data and sizes are being stored).

**Setting sizes with properties**
Along the way there has been some discussion of allowing sizes to be set as a function of a property. I had initially been in favor of doing so, upon further consideration, it seems pretty redundant, as the property will just be a column of numbers, which is what the size property already is.  Although, I can see the argument the if the user already has properties in a dataframe, it's just easier for them to pass that to the layer and assign properties via column names as opposed to splitting it up outside of napari and passing the pieces in. @sofroniewn , I think I was discussing this with you, was that the rationale you had in mind?

**Comment by adamltyson** [comment]
Hi @kevinyamauchi. All looks great from my end. I've put together a rudimentary [training data generation interface](https://github.com/SainsburyWellcomeCentre/cellfinder/blob/master/cellfinder/train/curation.py) for our cell detection software.

The only thing I couldn't work out how to do was to allow the user to select/deselect classes of points in the GUI (like you would be able to if they were two separate points layers). This isn't critical, but would be useful to visualise very dense points.

**Comment by kevinyamauchi** [comment]
@adamltyson , I haven't tested this, but I think the following will work:
```python
import numpy as np
point_indices_of_class = np.argwhere(
    viewer.layers[1].properties['point_class'] == class_value
)

points_layer.selected_data = point_indices_of_class

# If you are in the selection mode in 2D, you can call this to turn on the point highlight
point_layers._set_highlight()
```

Note that the highlighting only works when the viewer is in 2D mode and the points layer is in select mode.

Another alternative is to set the edge_color and face_color of the point class you want to "hide" to `'transparent'` (@HagaiHargil added this in #782). For example,

```python


# assuming you have a bool Points.property 'visible' 
# where True makes that points visible
face_color_cycle = ['green', 'transparent']
points_layer.face_color = 'visible'
points_layer.edge_color = 'visible'

# make class A invisible
visible_prop = points_layer.properties['visible']
class_prop = points_layer.properties['point_class']
visible_prop[class_prop == 'A'] = False

points_layer.properties['visible'] = visible_prop
points_layer.refresh_colors(update_color_mapping=False)

# or make only class A visible
visible_prop = points_layer.properties['visible']
class_prop_a = points_layer.properties['point_class'] == 'A'
points_layer.properties['visible'] = class_prop_a

points_layer.properties['visible'] = visible_prop
points_layer.refresh_colors(update_color_mapping=False)


```

**Comment by sofroniewn** [comment]
You'd need to hook up the code @kevinyamauchi mentions to a custom mouse function for this, say with a "shift-click" to selects all of one class. I'm not sure it is generic enough an operation for us to put in the core. Here is a link to a custom mouse function example https://github.com/napari/napari/blob/master/examples/custom_mouse_functions.py

**Comment by kevinyamauchi** [comment]
Also, cool application of napari, @adamltyson !

**Comment by kevinyamauchi** [comment]
@adamltyson , you could also try a pattern where you select a point or points and the when you press and hold a key, only points of that close or those classes are visible and then when you release the key, all of the points a visible again. See the [pan_zoom keybinding](https://github.com/napari/napari/blob/4414d284461b3d62b688591c97ed84a0d525552c/napari/layers/points/keybindings.py#L5) for an example of "press/release" keybindings. Sorry for the spam!

**Comment by jni** [comment]
@kevinyamauchi 

> Setting sizes with properties

Oh no no no no, this still *must* go in! Allow me to explain the rationale.

1. Consistency and data viz fundamentals

This will make size, face_color, and edge_color all be proper *channels* that data gets *encoded to* on the way to visualisation. This is a fundamental data viz principle that we should support fully, not half-assedly.

2. Setting different attributes to the point sizes from the GUI

Programmatically, it is not that different to say `add_points(..., sizes = table['propname'])` compared to `add_points(..., sizes='propname')`. However, when it comes to using the GUI, there is a *huge* difference between manually fiddling with selections and point sizes compared to selecting a column among a list of available columns.

3. Changing the point size *scale* independent of the data

Separating the scale (which can be n-dimensional) from the data means one can adjust all point sizes at once using a single slider. (And maybe ndim sliders on right-clicking, thanks again to @tlambert03!)

Hopefully the above points convince you that we still need to move sizes over to the new API! :blush:

**Comment by sofroniewn** [comment]
@kevinyamauchi I defer to @jni on the setting of size with columns, his argument makes sense to me. Also right now size is an `NxD` matrix and we're planning to more away from that - see #480 and #552. I plan to close #552 in favor of whatever you do here, so if you could also address #480 during this process that would be great - can be a single standalone PR.

**Comment by kevinyamauchi** [comment]
Hello @jni and @sofroniewn , sorry for the slow response. I am back in town and ready to pick this up again!

I agree with the points you raise and I will work on allowing size to be set by a property. I think the approach in #552 of having a layer size anisotropy and scalar point sizes makes sense. The one addition I might make is adding an additional layer size scaling factor. The layer size scaling factor will be connected to the size slider in the layer controls and allow the user to scale the size of the points while maintaining the anisotropy and relative sizing. I think users will want an easy way to adjust this for visualization purposes.
