### ISSUE TITLE
Remote data / compute meta issue

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#881]
## ❓ Questions and Help

This issue is a meta-issue trying to pull together various threads around our [remote and sharable napari efforts](https://github.com/napari/napari/projects/9)

I see two separate, but highly related use cases. The first is someone wants to view remote data (say from s3) but any compute on that data happens locally, the second is that someone wants to be doing interactive remote computing, say on ec2 or maybe some gpu machine they are sshed into.

### Remote data
Here, napari is already leveraging dask for lazy loading of big data that is local, and I think we want to continue to leverage things like the `dask_array.from_zarr` method where you can give s3 links. Here we still have a number of improvements to make though

- [ ] Drop repeated calls to `layer._set_view_slice` #845, so say if a slider is suddenly moved to 10 places you'd drop all but the last call.

- [ ] Make layer.refresh be non-blocking / happen on its own thread, #845. I have less understanding of this, but ideally we wouldn't be waiting for a dask / np.asarray call to finish to need to continue interacting with the GUI

- [ ] Better use of caching to make sure we don't load data back in that we have already loaded in. See #718

- [ ] Predictive caching. Say when looking at a pyramid or looking at a movie, if there is down time and there is space in the cache we might want to grab the next tiles or the next frames under the reasonable assumption they might be looked at next

- [ ] Make loading of tiff / directories of pngs directly into dask from places like s3 possible. dask-image does some of this now for local data, but I don't think does it for s3 data.

- [ ] Make sure we support non-image remote data too, say csv, json / whatever we end up using for shapes / points on disk data representations.

- [ ] Support remote data on google drive - see this thread https://github.com/pangeo-data/pangeo/issues/288. A lot of academics have free access to google drive, so it would be nice to be able to load data off of google drive directly into dask. There is some discussion on this thread on how to approach this.

- [ ] Make remote pyramid adding work with s3 paths 

### Remote compute

Here there are a couple different approaches we could take. I think a use-case that we know we want to support is someone who is now using a remote jupyter notebook or controlling a remote IPython console via ssh. There are a couple of approaches we could take

1. Drop Qt and OpenGL and move to a Javascript / Html + webGL front end and rendering system. This could give us direct compatibility with remote jupyter lab, and set us up for web versions of napari. Another nice thing about this approach is that the user continues to use the same napari APIs like when they are local and "things just work", but I don't think it is the direction we want to take the project right now. One reason for that is it then creates more a of barrier between the python code (where we want to be doing analyses) and the visualization code. There could be rendering performance hits with webGL that we wouldn't want a fully local user to have to suffer, and I don't think we want to maintain two rendering systems / frontends. We also already have a lot of time and effort invested in our Qt frontend and it is working well for us. 

2. Drop OpenGL for WebGL but keep Qt, and use ssh -X and X11 forwarding to connect to the remote machines. Again the nice thing about this approach is the user can continue to use the same napari APIs like when they are local and "things just work". This approach is maybe less of a major change from 1. as we are keeping Qt, but we then still need to have a webGL canvas inside our Qt which is a bit strange, and it's not clear that the X11 forwarding will be better, we just know what we have now isn't working - see https://github.com/napari/napari/issues/799#issuecomment-565859004. There might be other GL things to try, but this again doesn't seem like where we want to go.

3. Have a complete viewer model on the remote machine that is synchronized bidirectionally with a local viewer using Dask. This approach is nice because again, the remote user can still use the same `add_image` etc commands, but it has a big overhead of syncing everything in both directions, and things might get out of sync, and it's not really clear you want all the info flowing back to the remote machine every time you say change a colormap or worse, move the camera(!!), on the local machine. If you want to change the viewer then you also have two places where you could do things (local / remote), and it may get confusing. We did explore this idea in #654 

4. Just have a `RemoteDataServer` or `RemoteDaskServer` that connects the remote machine to the local machine and allows you to send dask array and basic python type data to a local machine that you can then work with. From an API standpoint it might look like

```python
# on remote machine
from napari import RemoteDaskServer
rds = RemoteDaskServer() # prints out some address dask+tcp://127.0.0.1:61779
rds.add_data('data_name', big_array) # prints out some address dask+tp://127.0.0.1:61779::data_name
```

```python
# on local machine
viewer.add_image(path='dask+tcp://127.0.0.1:61779::data_name', contrast_limits=[0, 1])
```

Here the user would have to make sure the networking connections / permissions etc allowed the local and remote to see each other, but then dask would send the array data over, in a way that's not to dis-similar from the remote data section above. What's nice about this is we don't have to worry about 2-way communication and it will leverage a lot of the same performance improvements we do in the remote data section above. The downside is connecting the networking stuff maybe hard / error prone / more burden than users want.

5. We steer people towards launching a dask client and cluster directly from their local machine and then using that dask client to control their remote resources. Dask Fargate might be one approach to this. As the client is local you can just launch napari as before. The burden is now on the dask side to actually do the connection / networking stuff, and they need to then support the various cloud providers or people with gpu boxes that want to do analysis - but it is reasonable to say their ecosystem is trending in that direction. This is then quite similar to 4. and the remote data section above, in the sense that the better our remote data performance is, the better this performance will be too, but now compute can be happening remotely too.

### Conclusion
All in all I think we should press on making the remote data performance as good as possible and consider options 4. and 5. for remote compute. Thoughts everyone?

I'm tagging @mrocklin in case you want to follow progress on this issue / want to weigh in anywhere too

**Comment by sofroniewn** [comment]
I'll add that if we go with options 4. and 5. then figuring out how to make seemless connections to remote jupyter hubs and a local napari - see this discussion here https://forum.image.sc/t/image-viewer-for-python-notebooks/32976/11?u=sofroniewn for people requesting support for this use case

**Comment by mrocklin** [comment]
>  Make loading of tiff / directories of pngs directly into dask from places like s3 possible. dask-image does some of this now for local data, but I don't think does it for s3 data.

There is an issue here: https://github.com/dask/dask-image/issues/84

>  Make sure we support non-image remote data too, say csv, json / whatever we end up using for shapes / points on disk data representations.

These should be easier today.  The business people have been here before, so you're on a well trodden path.

> We steer people towards launching a dask client and cluster directly from their local machine and then using that dask client to control their remote resources. Dask Fargate might be one approach to this. As the client is local you can just launch napari as before. The burden is now on the dask side to actually do the connection / networking stuff, and they need to then support the various cloud providers or people with gpu boxes that want to do analysis - but it is reasonable to say their ecosystem is trending in that direction. This is then quite similar to 4. and the remote data section above, in the sense that the better our remote data performance is, the better this performance will be too, but now compute can be happening remotely too.

Yeah, just to echo the sentiment here, there are a lot of people right now (open source and commercial) who are currently thinking about how to make it as easy as possible to run Dask in the cloud.  I think that if you are on this path that you'll have lots of company.

**Comment by marciovm** [comment]
Super excited here.

Building on use case #2 @sofroniewn mentioned (interactive remote computing), a related use case is a handoff from an analyst to a non-coding stakeholder like a PI. It would be great if this can be accomplished by passing a URL, with some coordination with the Dask server to handle any auth requirement. @mrocklin is this something the Dask-on-cloud folks are considering now?

**Comment by sofroniewn** [comment]
To get a sense of some of the current limitations of napari with big remote data you can run

```python
import napari
import dask.array as da

path = 'https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/9822151.zarr'
resolutions = [da.from_zarr(path, component=str(i)) for i in list(range(11))]

with napari.gui_qt(startup_logo=True):
    viewer = napari.Viewer()
    viewer.add_image(resolutions)
```

with this dataset from https://forum.image.sc/t/publication-of-idr0083-sars-cov-2-up-close-in-a-human-organoid/37163

**Comment by mrocklin** [comment]
Oh yeah, wow, that is definitely not a good experience.  

`<puts on for-profit hat>` 
Let me know if you all ever want to partner on making that smoother.  It seems like running computations in close to the data (including aggregating down), improving async operations, and generally enabling auth and sharing clusters between users would go a long way to making that a more pleasant experience.
`</takes off for-profit hat>`

> It would be great if this can be accomplished by passing a URL, with some coordination with the Dask server to handle any auth requirement. @mrocklin is this something the Dask-on-cloud folks are considering now?

Oh, sorry I missed this many months ago.  Yes, creating a team authentication structure around Dask resources in the cloud is definitely something that we're working on.  @sofroniewn has access to a very early version of this which is currently insecure, but has, I think, enough of the auth story to launch clusters, add people, give access, and so on.

**Comment by sofroniewn** [comment]
Indeed, as we zoom in we should non-blocking fetch the higher resolution data while still showing the lower-resolution data and then just rapidly switch in the high-res once it has all arrived - or in pieces as it arrives if we want to get really fancy ;-). @pwinston will be working on this and related performance issues over the next few months.
