### ISSUE TITLE
Plans for plugin PRs

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#936]
To keep reviewing manageable (and to encourage collaboration), I'm going to keep the plugin PRs as small as possible.  #908 lays the groundwork, and here are my plans for follow-up PRs.  I will update this as we progress.  (and feel free to comment/add items)

- [x] merge #908 🎉
- [x] #937: actually hook up the `napari_get_reader` hook (created in #908) to file io in napari. 🎉
- [x] https://github.com/pytest-dev/pluggy/pull/251 is merged!
  - [ ] ~~bump pluggy dependency and update docs when it is released~~.  (or, if it takes a long time, implement it internally)
  - [x] we now have our own fork at [napari-plugin-engine ](https://github.com/napari/napari-plugin-engine)
- [x] create a [cookiecutter](https://github.com/cookiecutter/cookiecutter) template for napari plugins, to make it easier for developers to get started.
  - https://github.com/napari/cookiecutter-napari-plugin
- [x] #1023: add methods to facilitate reordering of hooks, particularly those that use `firstresult=True`.
  - _by default, pluggy calls hooks in [last-in-first-out registered order](https://pluggy.readthedocs.io/en/latest/#call-time-order).  We will want to give users finer-tuned control over that, such as for reader plugins where the first one wins._
  - This won't be too hard, and I started a discussion about it at https://github.com/pytest-dev/pluggy/issues/250.
  - [x] create [QListWidget](https://doc.qt.io/qt-5/qlistwidget.html) gui that lets users drag/drop registered plugins to change call-order for specific hookspecs. started in #1023
- [x] #1024: provide user-facing GUI to easily send traceback information to developers to autopopulate a new issue at the developer's github issues.
- [x] #1030: add more verbose, developer-focused plugin documentation to the sphinx docs, and make sure the `hookspecs` page renders nicely (something like [how pytest does it](https://docs.pytest.org/en/latest/reference.html#hooks))
- [x] #1096: add loaded plugins to `sys_info` and the about window.
- [ ] ~~#935~~: discuss need for & finish implementing hook implementation tests/validation
    - I closed that PR.  We can reopen at a later date if needed.  To recap the general idea is to try to provide some sort of testing or validation on hook implementations.  For instance, do they execute in a specified amount of time without error?  A big challenge though is that we don't necessarily know what type of data they need.
- [ ] look through codebase for good places to replace internal functionality with hooks
  - [ ] themes

**Comment by sofroniewn** [comment]
@tlambert03 @jni at the EOSS meeting one of the matplotlib maintainers recommended https://pypi.org/project/entrypoints/ https://entrypoints.readthedocs.io/en/latest/ for very lightweight plugin stuff. I just wanted to surface this, it might target a slightly different use case then pluggy though. I wasn't sure. Thoughts?

**Comment by tlambert03** [comment]
from what I can tell, the main offering there is a helper function to discover packages that offer a particular `entry_point` group... which is pretty much exactly what our `plugins.manager.entry_points_for(group)` function does using the builtin [`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html) module:

https://github.com/napari/napari/blob/723c937d47c266aa37916c3ab5f06ca4daf7ffaf/napari/plugins/manager.py#L226-L258

**Comment by sofroniewn** [comment]
Makes sense @tlambert03, thanks for checking that out!!
